"""
DocuMotion - Pydantic 스키마 (요청/응답 모델)
"""
from __future__ import annotations
from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel


# ─────────────────────────────────────────────
# Slide 스키마
# ─────────────────────────────────────────────
class SlideBase(BaseModel):
    order_index: int = 0
    image_filename: str = ""
    label: str = ""
    text: str = ""
    # Video Slide
    slide_type: str = "image"
    video_filename: str = ""
    volume: float = 1.0
    subtitles: str = "[]"
    use_tts: int = 1  # 1=TTS 생성, 0=자막만
    trim_start: float = 0.0
    trim_end: float = 0.0


class SlideCreate(SlideBase):
    pass


class SlideUpdate(BaseModel):
    id: str
    order_index: int
    image_filename: str = ""
    label: str = ""
    text: str = ""
    # Video Slide
    slide_type: str = "image"
    video_filename: str = ""
    volume: float = 1.0
    subtitles: str = "[]"
    use_tts: int = 1  # 1=TTS 생성, 0=자막만
    trim_start: float = 0.0
    trim_end: float = 0.0


class SlideRead(SlideBase):
    id: str
    
    # Video Slide Fields Explicitly Added for Serialization
    slide_type: str = "image"
    video_filename: str = ""
    volume: float = 1.0
    subtitles: str = "[]"
    use_tts: int = 1
    trim_start: float = 0.0
    trim_end: float = 0.0

    model_config = {"from_attributes": True}


# ─────────────────────────────────────────────
# Project 스키마
# ─────────────────────────────────────────────
class ProjectCreate(BaseModel):
    name: str


class ProjectRead(BaseModel):
    id: str
    name: str
    status: str
    stage: str
    progress: int
    message: str
    has_video: bool = False
    slide_count: int = 0
    created_at: datetime
    updated_at: datetime

    model_config = {"from_attributes": True}


class ProjectDetail(ProjectRead):
    slides: List[SlideRead] = []


# ─────────────────────────────────────────────
# 렌더링 / 유튜브 스키마
# ─────────────────────────────────────────────
class RenderStatus(BaseModel):
    status: str
    progress: int
    message: str


class YouTubeUploadRequest(BaseModel):
    title: str
    description: str = "Generated by DocuMotion"
    tags: Optional[str] = None
