import { useState, useEffect, useRef, useCallback } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { api, Slide, ProjectDetail } from '../api/client'
import { useToast } from '../components/ToastContext'

// ─── YouTube Modal ────────────────────────────
function YouTubeModal({ projectId, projectName, onClose }: {
  projectId: string; projectName: string; onClose: () => void
}) {
  const { toast } = useToast()
  const [title, setTitle]       = useState(projectName)
  const [desc, setDesc]         = useState('Generated by DocuMotion')
  const [tags, setTags]         = useState('')
  const [loading, setLoading]   = useState(false)

  const handleUpload = async () => {
    setLoading(true)
    try {
      const { url } = await api.uploadYouTube(projectId, { title, description: desc, tags: tags || undefined })
      toast(`✅ 업로드 완료! ${url}`, 'success')
      onClose()
    } catch (e: unknown) {
      toast(e instanceof Error ? e.message : '업로드 실패', 'error')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal" onClick={e => e.stopPropagation()}>
        <div className="modal-header">
          <span className="modal-title">📺 YouTube 업로드</span>
          <button className="btn btn-ghost btn-icon" onClick={onClose}>✕</button>
        </div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          <div>
            <label className="label">제목</label>
            <input className="input" value={title} onChange={e => setTitle(e.target.value)} />
          </div>
          <div>
            <label className="label">설명</label>
            <textarea className="textarea" value={desc} onChange={e => setDesc(e.target.value)} rows={3} />
          </div>
          <div>
            <label className="label">태그 (쉼표로 구분)</label>
            <input className="input" value={tags} onChange={e => setTags(e.target.value)} placeholder="태그1, 태그2" />
          </div>
        </div>
        <div className="modal-footer">
          <button className="btn btn-secondary" onClick={onClose}>취소</button>
          <button className="btn btn-primary" onClick={handleUpload} disabled={loading}>
            {loading ? <><span className="spinner" /> 업로드 중...</> : '📤 업로드'}
          </button>
        </div>
      </div>
    </div>
  )
}

// ─── JSON Batch Modal ────────────────────────
function JsonModal({ slides, onApply, onClose }: {
  slides: Slide[]; onApply: (updated: Slide[]) => void; onClose: () => void
}) {
  const { toast } = useToast()
  const [json, setJson] = useState('')

  const handleApply = () => {
    try {
      const clean = json.replace(/\[cite.*?\]/g, '')
      const data: Record<string, string> = JSON.parse(clean)
      const updated = slides.map((s, i) => {
        if (data[String(i)] !== undefined) return { ...s, text: data[String(i)] }
        return s
      })
      const count = Object.keys(data).filter(k => parseInt(k) < slides.length).length
      onApply(updated)
      toast(`${count}개 슬라이드 대사 적용 완료`, 'success')
      onClose()
    } catch (e) {
      toast('JSON 형식 오류. 예: {"0": "텍스트", "1": "텍스트"}', 'error')
    }
  }

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal" style={{ maxWidth: 600 }} onClick={e => e.stopPropagation()}>
        <div className="modal-header">
          <span className="modal-title">🛠️ JSON 대사 일괄 입력</span>
          <button className="btn btn-ghost btn-icon" onClick={onClose}>✕</button>
        </div>
        <p style={{ color: 'var(--text-secondary)', fontSize: '0.8rem', marginBottom: '0.75rem' }}>
          형식: {`{"0": "첫번째 슬라이드 대사", "1": "두번째 슬라이드 대사"}`}
        </p>
        <textarea
          className="textarea"
          value={json}
          onChange={e => setJson(e.target.value)}
          rows={8}
          placeholder='{"0": "텍스트", "1": "텍스트"}'
          style={{ fontFamily: 'monospace', fontSize: '0.85rem' }}
        />
        <div className="modal-footer">
          <button className="btn btn-secondary" onClick={onClose}>취소</button>
          <button className="btn btn-primary" onClick={handleApply}>✅ 적용</button>
        </div>
      </div>
    </div>
  )
}

// ─── Subtitle Entry Type ─────────────────────
interface SubEntry { start: string; end: string; text: string; use_tts: boolean }

function parseSubtitles(raw: string): SubEntry[] {
  try { return JSON.parse(raw || '[]') } catch { return [] }
}
function serializeSubtitles(subs: SubEntry[]): string {
  return JSON.stringify(subs.map(s => ({
    start: parseFloat(s.start) || 0,
    end: parseFloat(s.end) || 0,
    text: s.text,
    use_tts: s.use_tts,
  })))
}
function mmssToSec(t: string): string {
  const m = t.match(/^(\d+):(\d{2})$/)
  if (m) return String(parseInt(m[1]) * 60 + parseInt(m[2]))
  return t
}
function secToMmss(v: number | string): string {
  const s = parseFloat(String(v)) || 0
  const m = Math.floor(s / 60), sec = Math.floor(s % 60)
  return `${m}:${String(sec).padStart(2, '0')}`
}

// ─── Slide Card ──────────────────────────────
function SlideCard({ slide, index, total, projectId, onUpdate, onDelete, onMoveUp, onMoveDown }: {
  slide: Slide; index: number; total: number; projectId: string
  onUpdate: (s: Slide) => void
  onDelete: () => void
  onMoveUp: () => void
  onMoveDown: () => void
}) {
  const [text, setText] = useState(slide.text)
  const [volume, setVolume] = useState(slide.volume ?? 1.0)
  const [useTts, setUseTts] = useState<boolean>((slide.use_tts ?? 1) === 1)
  const [subs, setSubs] = useState<SubEntry[]>(() => parseSubtitles(slide.subtitles))
  const videoRef = useRef<HTMLVideoElement>(null)

  useEffect(() => { setText(slide.text) }, [slide.text])
  useEffect(() => { setVolume(slide.volume ?? 1.0) }, [slide.volume])
  useEffect(() => { setUseTts((slide.use_tts ?? 1) === 1) }, [slide.use_tts])
  useEffect(() => { setSubs(parseSubtitles(slide.subtitles)) }, [slide.subtitles])

  const handleBlur = () => {
    if (text !== slide.text) onUpdate({ ...slide, text })
  }
  const handleVolumeChange = (v: number) => {
    setVolume(v)
    if (videoRef.current) videoRef.current.volume = v
    onUpdate({ ...slide, volume: v })
  }
  const handleSubChange = (idx: number, field: keyof SubEntry, val: string | boolean) => {
    const next = subs.map((s, i) => i === idx ? { ...s, [field]: val } : s)
    setSubs(next)
    onUpdate({ ...slide, subtitles: serializeSubtitles(next) })
  }
  const handleAddSub = () => {
    const next = [...subs, { start: '0:00', end: '0:05', text: '', use_tts: false }]
    setSubs(next)
    onUpdate({ ...slide, subtitles: serializeSubtitles(next) })
  }
  const handleDeleteSub = (idx: number) => {
    const next = subs.filter((_, i) => i !== idx)
    setSubs(next)
    onUpdate({ ...slide, subtitles: serializeSubtitles(next) })
  }

  const isVideo = slide.slide_type === 'video'

  return (
    <div className="card" style={{ padding: '1rem', display: 'grid', gridTemplateColumns: isVideo ? '1fr 40px' : '120px 1fr 40px', gap: '1rem', alignItems: 'start' }}>
      {/* Image Slide: Thumbnail */}
      {!isVideo && (
        <div style={{ borderRadius: 'var(--radius-sm)', overflow: 'hidden', background: 'var(--bg-secondary)', aspectRatio: '16/9', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
          {slide.image_filename ? (
            <img
              src={api.assetUrl(projectId, slide.image_filename)}
              alt={`Slide ${index + 1}`}
              style={{ width: '100%', height: '100%', objectFit: 'contain' }}
              onError={e => { (e.target as HTMLImageElement).src = '' }}
            />
          ) : (
            <span style={{ color: 'var(--text-muted)', fontSize: '1.5rem' }}>🖼️</span>
          )}
        </div>
      )}

      {/* Center Content */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
        <label className="label">
          {isVideo ? '🎬' : '🖼️'} Slide {index + 1} — {slide.label || slide.video_filename || slide.image_filename}
        </label>

        {/* Video Slide: preview + volume + subtitles */}
        {isVideo ? (
          <>
            {slide.video_filename && (
              <video
                ref={videoRef}
                controls
                style={{ width: '100%', maxHeight: 200, borderRadius: 'var(--radius-sm)', background: '#000' }}
                src={api.assetUrl(projectId, slide.video_filename)}
              />
            )}
            {/* Volume */}
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <span style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', whiteSpace: 'nowrap' }}>🔊 볼륨</span>
              <input
                type="range" min={0} max={1} step={0.05}
                value={volume}
                style={{ flex: 1 }}
                onChange={e => handleVolumeChange(parseFloat(e.target.value))}
              />
              <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)', width: 36 }}>{Math.round(volume * 100)}%</span>
            </div>
            {/* Subtitle Row Editor */}
            <div>
              <div style={{ fontSize: '0.85rem', fontWeight: 600, marginBottom: '0.4rem', color: 'var(--text-secondary)' }}>📝 자막</div>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.8rem' }}>
                <thead>
                  <tr style={{ color: 'var(--text-muted)' }}>
                    <th style={{ padding: '2px 6px', textAlign: 'left', width: 68 }}>시작</th>
                    <th style={{ padding: '2px 6px', textAlign: 'left', width: 68 }}>종료</th>
                    <th style={{ padding: '2px 6px', textAlign: 'left' }}>자막 텍스트</th>
                    <th style={{ padding: '2px 6px', width: 44 }}>TTS</th>
                    <th style={{ width: 28 }}></th>
                  </tr>
                </thead>
                <tbody>
                  {subs.map((s, idx) => (
                    <tr key={idx} style={{ borderTop: '1px solid var(--border)' }}>
                      <td style={{ padding: '3px 4px' }}>
                        <input className="input" style={{ padding: '2px 4px', fontSize: '0.78rem' }}
                          value={s.start} placeholder="0:00"
                          onChange={e => handleSubChange(idx, 'start', mmssToSec(e.target.value))}
                          onBlur={e => handleSubChange(idx, 'start', secToMmss(parseFloat(e.target.value) || 0))}
                        />
                      </td>
                      <td style={{ padding: '3px 4px' }}>
                        <input className="input" style={{ padding: '2px 4px', fontSize: '0.78rem' }}
                          value={s.end} placeholder="0:05"
                          onChange={e => handleSubChange(idx, 'end', mmssToSec(e.target.value))}
                          onBlur={e => handleSubChange(idx, 'end', secToMmss(parseFloat(e.target.value) || 0))}
                        />
                      </td>
                      <td style={{ padding: '3px 4px' }}>
                        <input className="input" style={{ padding: '2px 4px', fontSize: '0.78rem', width: '100%' }}
                          value={s.text} placeholder="자막 내용..."
                          onChange={e => handleSubChange(idx, 'text', e.target.value)}
                        />
                      </td>
                      <td style={{ padding: '3px 4px', textAlign: 'center' }}>
                        <input type="checkbox" checked={s.use_tts}
                          onChange={e => handleSubChange(idx, 'use_tts', e.target.checked)}
                          title="TTS 음성 생성"
                        />
                      </td>
                      <td style={{ padding: '3px 4px', textAlign: 'center' }}>
                        <button className="btn btn-danger btn-icon" style={{ fontSize: '0.75rem', padding: '2px 5px' }}
                          onClick={() => handleDeleteSub(idx)}>🗑</button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
              <button className="btn btn-ghost" style={{ marginTop: '0.4rem', fontSize: '0.8rem', padding: '4px 10px' }}
                onClick={handleAddSub}>+ 자막 추가</button>
            </div>
          </>
        ) : (
          /* Image Slide: text + TTS 토글 */
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
            <textarea
              className="textarea"
              value={text}
              onChange={e => setText(e.target.value)}
              onBlur={() => { if (text !== slide.text) onUpdate({ ...slide, text }) }}
              placeholder="TTS 대사 / 자막 텍스트를 입력하세요..."
              rows={4}
            />
            <label style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', fontSize: '0.85rem', cursor: 'pointer', color: 'var(--text-secondary)' }}>
              <input
                type="checkbox"
                checked={useTts}
                onChange={e => {
                  const v = e.target.checked
                  setUseTts(v)
                  onUpdate({ ...slide, use_tts: v ? 1 : 0 })
                }}
              />
              🔊 TTS 음성 생성 {useTts ? '(켜짐 — 음성 + 자막)' : '(꺼짐 — 자막만)'}
            </label>
          </div>
        )}
      </div>

      {/* Controls */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '0.3rem' }}>
        <button className="btn btn-ghost btn-icon" title="위로" onClick={onMoveUp} disabled={index === 0}>⬆️</button>
        <button className="btn btn-ghost btn-icon" title="아래로" onClick={onMoveDown} disabled={index === total - 1}>⬇️</button>
        <button className="btn btn-danger btn-icon" title="삭제" onClick={onDelete}>🗑️</button>
      </div>
    </div>
  )
}


// ─── Main Component ──────────────────────────
export default function Editor() {
  const { id: projectId } = useParams<{ id: string }>()
  const navigate = useNavigate()
  const { toast } = useToast()

  const [project, setProject]   = useState<ProjectDetail | null>(null)
  const [slides, setSlides]     = useState<Slide[]>([])
  const [loading, setLoading]   = useState(true)
  const [saving, setSaving]     = useState(false)
  const [uploading, setUploading] = useState(false)
  const [rendering, setRendering] = useState(false)
  const [progress, setProgress]   = useState(0)
  const [progressMsg, setProgressMsg] = useState('')
  const [insertAt, setInsertAt]     = useState(-1)
  const [showJson, setShowJson]     = useState(false)
  const [showYoutube, setShowYoutube] = useState(false)
  const [isDragging, setIsDragging] = useState(false)
  
  const fileInputRef  = useRef<HTMLInputElement>(null)
  const videoInputRef = useRef<HTMLInputElement>(null)
  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null)

  const loadProject = useCallback(async () => {
    if (!projectId) return
    try {
      const data = await api.getProject(projectId)
      setProject(data)
      setSlides(data.slides)
      if (['QUEUED', 'PROCESSING'].includes(data.status)) {
        setRendering(true)
        setProgress(data.progress)
        setProgressMsg(data.message)
      } else {
        setRendering(false)
      }
    } catch (e) {
      toast('프로젝트를 불러올 수 없습니다', 'error')
      navigate('/')
    } finally {
      setLoading(false)
    }
  }, [projectId, navigate, toast])

  useEffect(() => { loadProject() }, [loadProject])

  // Render polling
  useEffect(() => {
    if (!rendering || !projectId) { if (pollRef.current) clearInterval(pollRef.current); return }
    pollRef.current = setInterval(async () => {
      try {
        const s = await api.getRenderStatus(projectId)
        setProgress(s.progress)
        setProgressMsg(s.message)
        if (!['QUEUED', 'PROCESSING'].includes(s.status)) {
          setRendering(false)
          clearInterval(pollRef.current!)
          await loadProject()
          if (s.status === 'COMPLETED') toast('🎉 렌더링 완료!', 'success')
          else if (s.status === 'ERROR') toast(`오류: ${s.message}`, 'error')
        }
      } catch { clearInterval(pollRef.current!) }
    }, 2000)
    return () => { if (pollRef.current) clearInterval(pollRef.current) }
  }, [rendering, projectId, loadProject, toast])

  const handleSave = async () => {
    if (!projectId) return
    setSaving(true)
    try {
      const reindexed = slides.map((s, i) => ({ ...s, order_index: i }))
      await api.saveSlides(projectId, reindexed)
      setSlides(reindexed)
      toast('저장 완료', 'success')
    } catch (e: unknown) {
      toast(e instanceof Error ? e.message : '저장 실패', 'error')
    } finally {
      setSaving(false)
    }
  }

  const processFiles = async (files: File[]) => {
    if (!files.length || !projectId) return
    setUploading(true)
    try {
      const newSlides = await api.uploadSlides(projectId, files, insertAt)
      setSlides(prev => {
        const insertIdx = insertAt === -1 ? prev.length : Math.min(insertAt, prev.length)
        const updated = [...prev.slice(0, insertIdx), ...newSlides, ...prev.slice(insertIdx)]
        return updated.map((s, idx) => ({ ...s, order_index: idx }))
      })
      toast(`${newSlides.length}장 업로드 완료!`, 'success')
      setInsertAt(-1)
    } catch (e: unknown) {
      toast(e instanceof Error ? e.message : '업로드 실패', 'error')
    } finally {
      setUploading(false)
      if (fileInputRef.current) fileInputRef.current.value = ''
    }
  }

  const handleUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    processFiles(Array.from(e.target.files || []))
  }

  const handleVideoUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file || !projectId) return
    setUploading(true)
    try {
      const insertIdx = insertAt === -1 ? undefined : insertAt
      const newSlides = await api.uploadVideoSlide(projectId, file, insertIdx)
      setSlides(prev => {
        const idx = insertAt === -1 ? prev.length : Math.min(insertAt, prev.length)
        const updated = [...prev.slice(0, idx), ...newSlides, ...prev.slice(idx)]
        return updated.map((s, i) => ({ ...s, order_index: i }))
      })
      toast('동영상 슬라이드 추가 완료!', 'success')
      setInsertAt(-1)
    } catch (err: unknown) {
      toast(err instanceof Error ? err.message : '동영상 업로드 실패', 'error')
    } finally {
      setUploading(false)
      if (videoInputRef.current) videoInputRef.current.value = ''
    }
  }

  // Drag & Drop Handlers
  const onDragOver = (e: React.DragEvent) => {
    e.preventDefault()
    e.stopPropagation()
    setIsDragging(true)
  }
  
  const onDragLeave = (e: React.DragEvent) => {
    e.preventDefault()
    e.stopPropagation()
    setIsDragging(false)
  }
  
  const onDrop = (e: React.DragEvent) => {
    e.preventDefault()
    e.stopPropagation()
    setIsDragging(false)
    if (e.dataTransfer.files && e.dataTransfer.files.length > 0) {
      processFiles(Array.from(e.dataTransfer.files))
    }
  }

  const handleRender = async () => {
    if (!projectId) return
    const unsaved = slides.map((s, i) => ({ ...s, order_index: i }))
    await api.saveSlides(projectId, unsaved)
    try {
      await api.startRender(projectId)
      setRendering(true)
      setProgress(0)
      setProgressMsg('렌더링 대기 중...')
      toast('렌더링 시작됨', 'info')
    } catch (e: unknown) {
      toast(e instanceof Error ? e.message : '렌더링 시작 실패', 'error')
    }
  }

  const moveSlide = (i: number, dir: -1 | 1) => {
    const arr = [...slides]
    ;[arr[i], arr[i + dir]] = [arr[i + dir], arr[i]]
    setSlides(arr)
  }

  const deleteSlide = async (i: number) => {
    if (!projectId) return
    const slide = slides[i]
    try {
      await api.deleteSlide(projectId, slide.id)
      setSlides(prev => prev.filter((_, idx) => idx !== i))
    } catch (e: unknown) {
      toast(e instanceof Error ? e.message : '삭제 실패', 'error')
    }
  }

  const updateSlide = (i: number, updated: Slide) => {
    setSlides(prev => prev.map((s, idx) => idx === i ? updated : s))
  }

  if (loading) return (
    <div style={{ display: 'flex', justifyContent: 'center', padding: '6rem' }}>
      <span className="spinner spinner-lg" />
    </div>
  )

  const hasVideo = project?.has_video
  const isActive = rendering

  return (
    <div 
      style={{ display: 'grid', gridTemplateColumns: '260px 1fr', minHeight: 'calc(100vh - 64px)', position: 'relative' }}
      onDragOver={onDragOver}
      onDragLeave={onDragLeave}
      onDrop={onDrop}
    >
      {/* Drag overlay */}
      {isDragging && (
        <div style={{
          position: 'absolute', top: 0, left: 0, right: 0, bottom: 0,
          background: 'rgba(59, 130, 246, 0.15)', backdropFilter: 'blur(2px)',
          border: '3px dashed var(--primary)', borderRadius: 'var(--radius-lg)',
          zIndex: 50, display: 'flex', alignItems: 'center', justifyContent: 'center',
          pointerEvents: 'none'
        }}>
          <div style={{ background: 'var(--bg-card)', padding: '2rem 3rem', borderRadius: 'var(--radius-md)', boxShadow: 'var(--shadow-lg)' }}>
            <h2 style={{ fontSize: '1.5rem', color: 'var(--primary)', margin: 0 }}>📁 여기에 파일 드롭</h2>
            <p style={{ marginTop: '0.5rem', color: 'var(--text-muted)' }}>여러 장의 이미지나 PDF를 한 번에 추가할 수 있습니다</p>
          </div>
        </div>
      )}
      
      {/* Sidebar */}
      <aside style={{ background: 'var(--bg-secondary)', borderRight: '1px solid var(--border)', padding: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1rem', position: 'sticky', top: '64px', height: 'calc(100vh - 64px)', overflowY: 'auto' }}>
        <button className="btn btn-secondary btn-full" onClick={() => navigate('/')}>
          🔙 목록으로
        </button>

        <hr className="divider" />

        {/* Upload */}
        <div>
          <label className="label">자료 업로드</label>
          <div style={{ marginBottom: '0.5rem' }}>
            <select
              className="input"
              value={insertAt}
              onChange={e => setInsertAt(Number(e.target.value))}
              style={{ width: '100%', padding: '0.4rem', fontSize: '0.85rem' }}
            >
              <option value={-1}>맨 끝에 추가</option>
              {slides.map((_, i) => (
                <option key={i} value={i}>{i + 1}번 슬라이드 앞에 추가</option>
              ))}
            </select>
          </div>
          <input
            ref={fileInputRef}
            type="file"
            accept="image/*,.pdf"
            multiple={true}
            style={{ display: 'none' }}
            onChange={handleUpload}
            id="file-upload"
          />
          <label htmlFor="file-upload" className="btn btn-secondary btn-full" style={{ cursor: 'pointer', display: 'flex', justifyContent: 'center' }}>
            {uploading ? <><span className="spinner" /> 업로드 중...</> : '📁 이미지/PDF 추가'}
          </label>
          {/* Video Upload */}
          <input
            ref={videoInputRef}
            type="file"
            accept="video/mp4,video/webm,video/quicktime,video/x-msvideo,video/x-matroska"
            style={{ display: 'none' }}
            onChange={handleVideoUpload}
            id="video-upload"
          />
          <label htmlFor="video-upload" className="btn btn-secondary btn-full" style={{ cursor: 'pointer', display: 'flex', justifyContent: 'center', marginTop: '0.3rem' }}>
            {uploading ? <><span className="spinner" /> 업로드 중...</> : '🎬 동영상 추가'}
          </label>
        </div>

        {/* JSON Batch */}
        <button className="btn btn-secondary btn-full" onClick={() => setShowJson(true)}>
          🛠️ JSON 대사 일괄 입력
        </button>

        <hr className="divider" />

        {/* Save */}
        <button className="btn btn-secondary btn-full" onClick={handleSave} disabled={saving}>
          {saving ? <><span className="spinner" /> 저장 중...</> : '💾 저장'}
        </button>

        {/* Render */}
        <button className="btn btn-primary btn-full" onClick={handleRender} disabled={isActive || slides.length === 0}>
          {isActive ? <><span className="spinner" /> 렌더링 중...</> : '🚀 렌더링 시작'}
        </button>

        {/* Render Progress */}
        {isActive && (
          <div>
            <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginBottom: '0.4rem' }}>
              {progressMsg} ({progress}%)
            </div>
            <div className="progress-bar-wrap">
              <div className="progress-bar-fill animate-pulse" style={{ width: `${Math.max(5, progress)}%` }} />
            </div>
          </div>
        )}

        {/* Render Error */}
        {!isActive && project?.status === 'ERROR' && (
          <div style={{
            background: 'rgba(239,68,68,0.1)', border: '1px solid rgba(239,68,68,0.4)',
            borderRadius: 'var(--radius-md)', padding: '0.75rem', fontSize: '0.78rem'
          }}>
            <div style={{ color: '#f87171', fontWeight: 700, marginBottom: '0.3rem' }}>❌ 렌더링 실패</div>
            <div style={{ color: 'var(--text-muted)', whiteSpace: 'pre-wrap', wordBreak: 'break-word' }}>{project.message}</div>
          </div>
        )}

        <hr className="divider" />

        {/* Video Preview */}
        {hasVideo && (
          <div>
            <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginBottom: '0.4rem', fontWeight: 600 }}>🎬 영상 미리보기</div>
            <video
              key={api.downloadUrl(projectId!)}
              controls
              style={{ width: '100%', borderRadius: 'var(--radius-md)', border: '1px solid var(--border)', background: '#000' }}
            >
              <source src={api.downloadUrl(projectId!)} type="video/mp4" />
            </video>
          </div>
        )}

        {/* Download */}
        {hasVideo && (
          <a className="btn btn-secondary btn-full" href={api.downloadUrl(projectId!)} download>
            💾 MP4 다운로드
          </a>
        )}

        {/* YouTube */}
        {hasVideo && (
          <button className="btn btn-secondary btn-full" onClick={() => setShowYoutube(true)}>
            📺 YouTube 업로드
          </button>
        )}
      </aside>

      {/* Main Content */}
      <main className="page" style={{ padding: '1.5rem' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>
          <div>
            <h2 style={{ fontSize: '1.4rem', fontWeight: 700 }}>📝 {project?.name}</h2>
            <p style={{ color: 'var(--text-muted)', fontSize: '0.8rem' }}>
              {slides.length} 슬라이드 · 변경 후 저장하거나 바로 렌더링하세요
            </p>
          </div>
        </div>

        {slides.length === 0 ? (
          <div className="empty-state">
            <div className="icon">🖼️</div>
            <h3>슬라이드가 없습니다</h3>
            <p>왼쪽 사이드바에서 이미지 또는 PDF를 업로드하세요</p>
          </div>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
            {slides.map((slide, i) => (
              <SlideCard
                key={slide.id}
                slide={slide}
                index={i}
                total={slides.length}
                projectId={projectId!}
                onUpdate={s => updateSlide(i, s)}
                onDelete={() => deleteSlide(i)}
                onMoveUp={() => moveSlide(i, -1)}
                onMoveDown={() => moveSlide(i, 1)}
              />
            ))}
          </div>
        )}
      </main>

      {/* Modals */}
      {showJson && (
        <JsonModal
          slides={slides}
          onApply={s => setSlides(s)}
          onClose={() => setShowJson(false)}
        />
      )}
      {showYoutube && project && (
        <YouTubeModal
          projectId={projectId!}
          projectName={project.name}
          onClose={() => setShowYoutube(false)}
        />
      )}
    </div>
  )
}
