import { useState, useEffect, useRef, useCallback } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { api, Slide, ProjectDetail } from '../api/client'
import { useToast } from '../components/ToastContext'
import GoogleAuthSection, { extractCodeFromUrl } from '../components/GoogleAuthSection'

// ─── YouTube Modal ────────────────────────────
function YouTubeModal({ projectId, projectName, onClose }: {
  projectId: string; projectName: string; onClose: () => void
}) {
  const { toast } = useToast()
  const [title, setTitle] = useState(projectName)
  const [desc, setDesc] = useState('Generated by DocuMotion')
  const [tags, setTags] = useState('')
  const [loading, setLoading] = useState(false)
  const [authStatus, setAuthStatus] = useState<'checking' | 'ok' | 'need_auth' | 'code_input'>('checking')
  const [codeInput, setCodeInput] = useState('')
  const [exchanging, setExchanging] = useState(false)

  useEffect(() => {
    api.youtubeAuthStatus().then(res => {
      setAuthStatus(res.authenticated ? 'ok' : 'need_auth')
    }).catch(() => setAuthStatus('need_auth'))
  }, [])

  const handleAuth = async () => {
    try {
      const { auth_url } = await api.youtubeAuthUrl()
      window.open(auth_url, '_blank')
      setAuthStatus('code_input')
      setCodeInput('')
    } catch (e: unknown) {
      toast(e instanceof Error ? e.message : '인증 URL 생성 실패', 'error')
    }
  }

  const handleExchangeCode = async () => {
    const code = extractCodeFromUrl(codeInput)
    if (!code) { toast('인증 코드를 입력해주세요', 'error'); return }
    setExchanging(true)
    try {
      await api.youtubeExchangeCode(code)
      toast('YouTube 인증 완료!', 'success')
      setAuthStatus('ok')
    } catch (e: unknown) {
      toast(e instanceof Error ? e.message : '코드 교환 실패', 'error')
    } finally {
      setExchanging(false)
    }
  }

  const handleUpload = async () => {
    setLoading(true)
    try {
      const { url } = await api.uploadYouTube(projectId, { title, description: desc, tags: tags || undefined })
      toast(`업로드 완료! ${url}`, 'success')
      onClose()
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : '업로드 실패'
      if (msg.includes('인증') || msg.includes('401')) {
        setAuthStatus('need_auth')
        toast('YouTube 인증이 필요합니다. 인증 후 다시 시도해주세요.', 'error')
      } else {
        toast(msg, 'error')
      }
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal" onClick={e => e.stopPropagation()}>
        <div className="modal-header">
          <span className="modal-title">YouTube 업로드</span>
          <button className="btn btn-ghost btn-icon" onClick={onClose}>✕</button>
        </div>

        {authStatus === 'checking' && (
          <div style={{ padding: '0.75rem', marginBottom: '1rem', borderRadius: 'var(--radius-sm)', background: 'var(--accent-light)', color: 'var(--text-secondary)', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <span className="spinner" /> 인증 상태 확인 중...
          </div>
        )}
        {authStatus === 'need_auth' && (
          <div style={{ padding: '0.75rem', marginBottom: '1rem', borderRadius: 'var(--radius-sm)', background: 'rgba(239,68,68,0.1)', border: '1px solid var(--error)', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <span style={{ color: 'var(--error)', fontSize: '0.875rem' }}>YouTube 인증이 필요합니다</span>
            <button className="btn btn-primary btn-sm" onClick={handleAuth}>Google 계정 인증</button>
          </div>
        )}
        {authStatus === 'code_input' && (
          <div style={{ padding: '0.75rem', marginBottom: '1rem', borderRadius: 'var(--radius-sm)', background: 'var(--bg-secondary)', border: '1px solid var(--border)' }}>
            <p style={{ color: 'var(--text-secondary)', fontSize: '0.8rem', marginBottom: '0.5rem', lineHeight: 1.5 }}>
              새 탭에서 Google 로그인 후, 주소창의 URL을 복사해서 붙여넣기하세요.
            </p>
            <input
              className="input"
              style={{ fontSize: '0.8rem', marginBottom: '0.4rem' }}
              placeholder="http://localhost?code=4/0A... 전체 URL"
              value={codeInput}
              onChange={e => setCodeInput(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && handleExchangeCode()}
            />
            <div style={{ display: 'flex', gap: '0.3rem' }}>
              <button className="btn btn-primary btn-sm" style={{ flex: 1 }} onClick={handleExchangeCode} disabled={exchanging}>
                {exchanging ? '처리 중...' : '인증 완료'}
              </button>
              <button className="btn btn-ghost btn-sm" onClick={() => setAuthStatus('need_auth')}>취소</button>
            </div>
          </div>
        )}
        {authStatus === 'ok' && (
          <div style={{ padding: '0.75rem', marginBottom: '1rem', borderRadius: 'var(--radius-sm)', background: 'rgba(34,197,94,0.1)', border: '1px solid var(--success)', color: 'var(--success)', fontSize: '0.875rem' }}>
            YouTube 인증됨
          </div>
        )}

        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          <div>
            <label className="label">제목</label>
            <input className="input" value={title} onChange={e => setTitle(e.target.value)} />
          </div>
          <div>
            <label className="label">설명</label>
            <textarea className="textarea" value={desc} onChange={e => setDesc(e.target.value)} rows={3} />
          </div>
          <div>
            <label className="label">태그 (쉼표로 구분)</label>
            <input className="input" value={tags} onChange={e => setTags(e.target.value)} placeholder="태그1, 태그2" />
          </div>
        </div>
        <div className="modal-footer">
          <button className="btn btn-secondary" onClick={onClose}>취소</button>
          <button className="btn btn-primary" onClick={handleUpload} disabled={loading || authStatus !== 'ok'}>
            {loading ? <><span className="spinner" /> 업로드 중...</> : '업로드'}
          </button>
        </div>
      </div>
    </div>
  )
}

// ─── Google Photos Picker Modal ───────────────
function GooglePhotosModal({ projectId, onClose, onImported }: {
  projectId: string; onClose: () => void; onImported: () => void
}) {
  const { toast } = useToast()
  const [authOk, setAuthOk] = useState<boolean | null>(null)
  const [phase, setPhase] = useState<'idle' | 'code_input' | 'picking' | 'importing' | 'done'>('idle')
  const [sessionId, setSessionId] = useState<string>('')
  const [codeInput, setCodeInput] = useState('')
  const [exchanging, setExchanging] = useState(false)
  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null)

  // 인증 확인
  useEffect(() => {
    api.photosAuthStatus().then(res => setAuthOk(res.authenticated)).catch(() => setAuthOk(false))
  }, [])

  // 폴링 정리
  useEffect(() => {
    return () => { if (pollRef.current) clearInterval(pollRef.current) }
  }, [])

  const handleAuth = async () => {
    try {
      const { auth_url } = await api.photosAuthUrl()
      window.open(auth_url, '_blank')
      setPhase('code_input')
      setCodeInput('')
    } catch (e: unknown) {
      toast(e instanceof Error ? e.message : '인증 URL 생성 실패', 'error')
    }
  }

  const handleExchangeCode = async () => {
    const code = extractCodeFromUrl(codeInput)
    if (!code) { toast('인증 코드를 입력해주세요', 'error'); return }
    setExchanging(true)
    try {
      await api.photosExchangeCode(code)
      toast('Google Photos 인증 완료!', 'success')
      setAuthOk(true)
      setPhase('idle')
    } catch (e: unknown) {
      toast(e instanceof Error ? e.message : '코드 교환 실패', 'error')
    } finally {
      setExchanging(false)
    }
  }

  const handleOpenPicker = async () => {
    try {
      // 1. Picker 세션 생성
      const session = await api.photosCreateSession()
      setSessionId(session.id)
      setPhase('picking')

      // 2. Picker UI 새 탭에서 열기
      window.open(session.pickerUri, '_blank')

      // 3. 세션 폴링 — 사용자 선택 완료 대기
      pollRef.current = setInterval(async () => {
        try {
          const status = await api.photosPollSession(session.id)
          console.log('[Photos] poll:', status)
          if (status.mediaItemsSet) {
            if (pollRef.current) clearInterval(pollRef.current)
            pollRef.current = null
            await doImport(session.id)
          }
        } catch (err) {
          console.error('[Photos] poll error:', err)
        }
      }, 3000)

    } catch (e: unknown) {
      toast(e instanceof Error ? e.message : 'Picker 세션 생성 실패', 'error')
      setPhase('idle')
    }
  }

  // 수동으로 가져오기 실행 (폴링이 자동 감지 못할 때 대비)
  const handleManualImport = async () => {
    if (!sessionId) return
    // 폴링 정리
    if (pollRef.current) { clearInterval(pollRef.current); pollRef.current = null }
    await doImport(sessionId)
  }

  const doImport = async (sid: string) => {
    setPhase('importing')
    try {
      const res = await api.photosImport(projectId, sid)
      toast(`${res.count}개 미디어 가져오기 완료!`, 'success')
      setPhase('done')
      onImported()
      onClose()
    } catch (e: unknown) {
      toast(e instanceof Error ? e.message : '가져오기 실패', 'error')
      setPhase('idle')
    }
  }

  return (
    <div className="modal-overlay" onClick={phase === 'idle' || phase === 'done' ? onClose : undefined}>
      <div className="modal" onClick={e => e.stopPropagation()} style={{ maxWidth: '500px' }}>
        <div className="modal-header">
          <span className="modal-title">Google Photos에서 가져오기</span>
          <button className="btn btn-ghost btn-icon" onClick={onClose} disabled={phase === 'importing'}>✕</button>
        </div>

        {/* 인증 확인 중 */}
        {authOk === null && (
          <div style={{ textAlign: 'center', padding: '2rem' }}>
            <span className="spinner" /> 인증 확인 중...
          </div>
        )}

        {/* 인증 안됨 */}
        {authOk === false && phase !== 'code_input' && (
          <div style={{ textAlign: 'center', padding: '2rem' }}>
            <p style={{ color: 'var(--text-secondary)', marginBottom: '1rem', fontSize: '0.9rem' }}>
              Google Photos 접근 권한이 필요합니다
            </p>
            <button className="btn btn-primary" onClick={handleAuth}>Google 계정 인증</button>
          </div>
        )}

        {/* 코드 입력 */}
        {phase === 'code_input' && (
          <div style={{ padding: '1.5rem' }}>
            <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem', marginBottom: '0.8rem', lineHeight: 1.6 }}>
              새 탭에서 Google 로그인 후,<br />
              주소창의 URL을 복사해서 아래에 붙여넣기하세요.
            </p>
            <input
              className="input"
              style={{ fontSize: '0.85rem', marginBottom: '0.6rem' }}
              placeholder="http://localhost?code=4/0A... 전체 URL"
              value={codeInput}
              onChange={e => setCodeInput(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && handleExchangeCode()}
              autoFocus
            />
            <div style={{ display: 'flex', gap: '0.5rem' }}>
              <button className="btn btn-primary" style={{ flex: 1 }} onClick={handleExchangeCode} disabled={exchanging}>
                {exchanging ? '처리 중...' : '인증 완료'}
              </button>
              <button className="btn btn-secondary" onClick={() => setPhase('idle')}>취소</button>
            </div>
          </div>
        )}

        {/* 인증됨 */}
        {authOk === true && (
          <div style={{ textAlign: 'center', padding: '1.5rem 1rem' }}>
            {phase === 'idle' && (
              <>
                <p style={{ color: 'var(--text-secondary)', marginBottom: '1.2rem', fontSize: '0.9rem', lineHeight: 1.6 }}>
                  Google Photos Picker가 새 창에서 열립니다.<br />
                  원하는 사진/동영상을 선택하면 자동으로 가져옵니다.
                </p>
                <button className="btn btn-primary" onClick={handleOpenPicker} style={{ fontSize: '1rem', padding: '0.7rem 2rem' }}>
                  사진 선택하기
                </button>
              </>
            )}

            {phase === 'picking' && (
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '1rem' }}>
                <span className="spinner spinner-lg" />
                <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', lineHeight: 1.6 }}>
                  Google Photos에서 사진을 선택해주세요...<br />
                  <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                    선택 완료 후 자동 진행됩니다
                  </span>
                </p>
                <button className="btn btn-primary" onClick={handleManualImport} style={{ marginTop: '0.5rem' }}>
                  선택 완료 — 가져오기
                </button>
                <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
                  자동으로 진행되지 않으면 위 버튼을 눌러주세요
                </p>
              </div>
            )}

            {phase === 'importing' && (
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '1rem' }}>
                <span className="spinner spinner-lg" />
                <p style={{ color: 'var(--accent)', fontSize: '0.9rem', fontWeight: 600 }}>
                  선택한 미디어를 다운로드하는 중...
                </p>
                <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                  파일 크기에 따라 시간이 걸릴 수 있습니다
                </p>
              </div>
            )}
          </div>
        )}

        <div className="modal-footer">
          <button className="btn btn-secondary" onClick={onClose} disabled={phase === 'importing'}>
            {phase === 'idle' ? '닫기' : '취소'}
          </button>
        </div>
      </div>
    </div>
  )
}

// ─── JSON Batch Modal ────────────────────────
function JsonModal({ slides, onApply, onClose }: {
  slides: Slide[]; onApply: (updated: Slide[]) => void; onClose: () => void
}) {
  const { toast } = useToast()
  const [json, setJson] = useState('')

  const handleApply = () => {
    try {
      const clean = json.replace(/\[cite.*?\]/g, '')
      const data: Record<string, string> = JSON.parse(clean)
      const updated = slides.map((s, i) => {
        if (data[String(i)] !== undefined) return { ...s, text: data[String(i)] }
        return s
      })
      const count = Object.keys(data).filter(k => parseInt(k) < slides.length).length
      onApply(updated)
      toast(`${count}개 슬라이드 대사 적용 완료`, 'success')
      onClose()
    } catch (e) {
      toast('JSON 형식 오류. 예: {"0": "텍스트", "1": "텍스트"}', 'error')
    }
  }

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal" style={{ maxWidth: 600 }} onClick={e => e.stopPropagation()}>
        <div className="modal-header">
          <span className="modal-title">🛠️ JSON 대사 일괄 입력</span>
          <button className="btn btn-ghost btn-icon" onClick={onClose}>✕</button>
        </div>
        <p style={{ color: 'var(--text-secondary)', fontSize: '0.8rem', marginBottom: '0.75rem' }}>
          형식: {`{"0": "첫번째 슬라이드 대사", "1": "두번째 슬라이드 대사"}`}
        </p>
        <textarea
          className="textarea"
          value={json}
          onChange={e => setJson(e.target.value)}
          rows={8}
          placeholder='{"0": "텍스트", "1": "텍스트"}'
          style={{ fontFamily: 'monospace', fontSize: '0.85rem' }}
        />
        <div className="modal-footer">
          <button className="btn btn-secondary" onClick={onClose}>취소</button>
          <button className="btn btn-primary" onClick={handleApply}>✅ 적용</button>
        </div>
      </div>
    </div>
  )
}

// ─── Global Settings Modal (6-10) ────────────
function GlobalSettingsModal({ project, onClose, onSave }: {
  project: ProjectDetail
  onClose: () => void
  onSave: (settings: Record<string, unknown>) => Promise<void>
}) {
  const [defaultTransition, setDefaultTransition] = useState(project.default_transition || 'none')
  const [defaultSlideDuration, setDefaultSlideDuration] = useState(project.default_slide_duration || 3.0)
  const [subtitleFontSize, setSubtitleFontSize] = useState(project.subtitle_font_size || 28)
  const [subtitleFontColor, setSubtitleFontColor] = useState(project.subtitle_font_color || 'white')
  const [watermarkText, setWatermarkText] = useState(project.watermark_text || '')
  const [watermarkOpacity, setWatermarkOpacity] = useState(project.watermark_opacity ?? 0.3)
  const [saving, setSaving] = useState(false)

  const FONT_COLORS = [
    { value: 'white', label: '흰색', color: '#fff' },
    { value: 'yellow', label: '노란색', color: '#facc15' },
    { value: '#00ff88', label: '초록색', color: '#00ff88' },
    { value: '#60a5fa', label: '파란색', color: '#60a5fa' },
    { value: '#f472b6', label: '분홍색', color: '#f472b6' },
    { value: '#fb923c', label: '주황색', color: '#fb923c' },
  ]

  const handleSave = async () => {
    setSaving(true)
    await onSave({
      default_transition: defaultTransition,
      default_slide_duration: defaultSlideDuration,
      subtitle_font_size: subtitleFontSize,
      subtitle_font_color: subtitleFontColor,
      watermark_text: watermarkText,
      watermark_opacity: watermarkOpacity,
    })
    setSaving(false)
  }

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal" style={{ maxWidth: 520, maxHeight: '85vh', overflow: 'auto' }} onClick={e => e.stopPropagation()}>
        <h2 style={{ margin: '0 0 1.2rem', fontSize: '1.1rem' }}>&#x2699;&#xFE0F; 전역 설정 (Master)</h2>

        {/* ── Default Transition ── */}
        <div style={{ marginBottom: '1rem' }}>
          <label className="label">기본 장면 전환 효과</label>
          <p style={{ fontSize: '0.72rem', color: 'var(--text-muted)', margin: '0 0 0.4rem' }}>
            새 슬라이드에 적용될 기본 전환 효과 (개별 설정 우선)
          </p>
          <select className="input" value={defaultTransition} onChange={e => setDefaultTransition(e.target.value)}
            style={{ width: '100%' }}>
            <option value="none">없음 (Hard Cut)</option>
            <option value="crossfade">크로스페이드</option>
            <option value="fade_black">페이드 투 블랙</option>
            <option value="slide_left">슬라이드 왼쪽</option>
            <option value="slide_right">슬라이드 오른쪽</option>
          </select>
        </div>

        {/* ── Default Slide Duration ── */}
        <div style={{ marginBottom: '1rem' }}>
          <label className="label">기본 슬라이드 시간</label>
          <p style={{ fontSize: '0.72rem', color: 'var(--text-muted)', margin: '0 0 0.4rem' }}>
            텍스트가 없는 이미지 슬라이드의 표시 시간
          </p>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <input type="range" min={1} max={15} step={0.5} value={defaultSlideDuration}
              style={{ flex: 1 }} onChange={e => setDefaultSlideDuration(parseFloat(e.target.value))} />
            <span style={{ fontSize: '0.85rem', fontWeight: 600, width: 42 }}>{defaultSlideDuration}초</span>
          </div>
        </div>

        {/* ── Subtitle Font Size ── */}
        <div style={{ marginBottom: '1rem' }}>
          <label className="label">자막 폰트 크기</label>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <input type="range" min={16} max={56} step={2} value={subtitleFontSize}
              style={{ flex: 1 }} onChange={e => setSubtitleFontSize(parseInt(e.target.value))} />
            <span style={{ fontSize: '0.85rem', fontWeight: 600, width: 42 }}>{subtitleFontSize}px</span>
          </div>
          {/* Preview */}
          <div style={{
            marginTop: '0.5rem', background: '#111', borderRadius: 'var(--radius-sm)',
            padding: '0.8rem', textAlign: 'center', position: 'relative', overflow: 'hidden'
          }}>
            <span style={{ fontSize: `${Math.min(subtitleFontSize * 0.6, 28)}px`, color: subtitleFontColor }}>
              자막 미리보기 Preview
            </span>
          </div>
        </div>

        {/* ── Subtitle Font Color ── */}
        <div style={{ marginBottom: '1rem' }}>
          <label className="label">자막 폰트 색상</label>
          <div style={{ display: 'flex', gap: '0.4rem', flexWrap: 'wrap' }}>
            {FONT_COLORS.map(c => (
              <button key={c.value} onClick={() => setSubtitleFontColor(c.value)}
                style={{
                  width: 36, height: 36, borderRadius: 'var(--radius-sm)',
                  background: c.color, border: subtitleFontColor === c.value ? '3px solid var(--accent)' : '2px solid var(--border)',
                  cursor: 'pointer', transition: 'all 0.15s',
                  boxShadow: subtitleFontColor === c.value ? '0 0 0 2px var(--accent-light)' : 'none'
                }}
                title={c.label}
              />
            ))}
            <input type="color" value={subtitleFontColor.startsWith('#') ? subtitleFontColor : '#ffffff'}
              onChange={e => setSubtitleFontColor(e.target.value)}
              style={{ width: 36, height: 36, border: '2px solid var(--border)', borderRadius: 'var(--radius-sm)', cursor: 'pointer', padding: 0 }}
              title="커스텀 색상"
            />
          </div>
        </div>

        {/* ── Watermark ── */}
        <div style={{ marginBottom: '1rem' }}>
          <label className="label">워터마크</label>
          <input className="input" value={watermarkText} placeholder="워터마크 텍스트 (비워두면 미적용)"
            onChange={e => setWatermarkText(e.target.value)} style={{ width: '100%', marginBottom: '0.4rem' }} />
          {watermarkText && (
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <span style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>불투명도</span>
              <input type="range" min={0.05} max={1} step={0.05} value={watermarkOpacity}
                style={{ flex: 1 }} onChange={e => setWatermarkOpacity(parseFloat(e.target.value))} />
              <span style={{ fontSize: '0.78rem', width: 36 }}>{Math.round(watermarkOpacity * 100)}%</span>
            </div>
          )}
        </div>

        {/* ── Actions ── */}
        <div style={{ display: 'flex', gap: '0.5rem', justifyContent: 'flex-end', marginTop: '1.2rem' }}>
          <button className="btn btn-ghost" onClick={onClose}>취소</button>
          <button className="btn btn-primary" onClick={handleSave} disabled={saving}>
            {saving ? '저장 중...' : '설정 저장'}
          </button>
        </div>
      </div>
    </div>
  )
}

// ─── Subtitle Entry Type ─────────────────────
interface SubEntry { start: string; end: string; text: string; use_tts: boolean }

function parseSubtitles(raw: string): SubEntry[] {
  try { return JSON.parse(raw || '[]') } catch { return [] }
}
function serializeSubtitles(subs: SubEntry[]): string {
  return JSON.stringify(subs.map(s => ({
    start: parseFloat(s.start) || 0,
    end: parseFloat(s.end) || 0,
    text: s.text,
    use_tts: s.use_tts,
  })))
}
function mmssToSec(t: string): string {
  const m = t.match(/^(\d+):(\d{2})$/)
  if (m) return String(parseInt(m[1]) * 60 + parseInt(m[2]))
  return t
}
function secToMmss(v: number | string): string {
  const s = parseFloat(String(v)) || 0
  const m = Math.floor(s / 60), sec = Math.floor(s % 60)
  return `${m}:${String(sec).padStart(2, '0')}`
}

// ─── Subtitle Interactive Timeline (6-12) ────
function SubtitleTimeline({ subs, videoDuration, onChange, videoRef }: {
  subs: SubEntry[]
  videoDuration: number
  onChange: (subs: SubEntry[]) => void
  videoRef: React.RefObject<HTMLVideoElement>
}) {
  const trackRef = useRef<HTMLDivElement>(null)
  const [dragging, setDragging] = useState<{ idx: number; type: 'move' | 'left' | 'right'; startX: number; origStart: number; origEnd: number } | null>(null)
  const [selectedIdx, setSelectedIdx] = useState<number | null>(null)

  const pxToSec = (px: number) => {
    if (!trackRef.current) return 0
    return (px / trackRef.current.clientWidth) * videoDuration
  }

  const handleMouseDown = (idx: number, type: 'move' | 'left' | 'right') => (e: React.MouseEvent) => {
    e.preventDefault()
    e.stopPropagation()
    const st = parseFloat(String(subs[idx].start)) || 0
    const en = parseFloat(String(subs[idx].end)) || 0
    setDragging({ idx, type, startX: e.clientX, origStart: st, origEnd: en })
    setSelectedIdx(idx)
  }

  useEffect(() => {
    if (!dragging) return
    const handleMove = (e: MouseEvent) => {
      const dx = e.clientX - dragging.startX
      const dSec = pxToSec(dx)
      const next = [...subs]
      const sub = { ...next[dragging.idx] }
      const minDur = 0.3

      if (dragging.type === 'move') {
        let newStart = dragging.origStart + dSec
        let newEnd = dragging.origEnd + dSec
        const dur = dragging.origEnd - dragging.origStart
        if (newStart < 0) { newStart = 0; newEnd = dur }
        if (newEnd > videoDuration) { newEnd = videoDuration; newStart = videoDuration - dur }
        sub.start = String(Math.max(0, newStart))
        sub.end = String(Math.min(videoDuration, newEnd))
      } else if (dragging.type === 'left') {
        const newStart = Math.max(0, Math.min(dragging.origEnd - minDur, dragging.origStart + dSec))
        sub.start = String(newStart)
      } else {
        const newEnd = Math.min(videoDuration, Math.max(dragging.origStart + minDur, dragging.origEnd + dSec))
        sub.end = String(newEnd)
      }
      next[dragging.idx] = sub
      onChange(next)
    }
    const handleUp = () => setDragging(null)
    window.addEventListener('mousemove', handleMove)
    window.addEventListener('mouseup', handleUp)
    return () => { window.removeEventListener('mousemove', handleMove); window.removeEventListener('mouseup', handleUp) }
  })

  const seekTo = (sec: number) => {
    if (videoRef.current) {
      videoRef.current.currentTime = sec
    }
  }

  const handleTrackClick = (e: React.MouseEvent) => {
    if (!trackRef.current) return
    const rect = trackRef.current.getBoundingClientRect()
    const sec = ((e.clientX - rect.left) / rect.width) * videoDuration
    seekTo(sec)
  }

  return (
    <div style={{ marginTop: '0.5rem' }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '0.25rem' }}>
        <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>타임라인 (드래그로 조절)</span>
        {selectedIdx !== null && subs[selectedIdx] && (
          <span style={{ fontSize: '0.68rem', color: 'var(--accent)' }}>
            #{selectedIdx + 1}: {(parseFloat(String(subs[selectedIdx].start)) || 0).toFixed(1)}s ~ {(parseFloat(String(subs[selectedIdx].end)) || 0).toFixed(1)}s
          </span>
        )}
      </div>
      <div
        ref={trackRef}
        onClick={handleTrackClick}
        style={{
          position: 'relative', height: 52, background: 'var(--bg-secondary)',
          borderRadius: 'var(--radius-sm)', border: '1px solid var(--border)',
          overflow: 'visible', cursor: 'pointer', userSelect: 'none'
        }}
      >
        {/* Time markers */}
        {Array.from({ length: Math.min(20, Math.ceil(videoDuration / 5)) }, (_, k) => {
          const t = (k + 1) * 5
          if (t >= videoDuration) return null
          return <div key={k} style={{
            position: 'absolute', left: `${(t / videoDuration) * 100}%`, top: 0, bottom: 0,
            borderLeft: '1px dashed var(--border-light)', zIndex: 0
          }}>
            <span style={{ position: 'absolute', top: 1, left: 2, fontSize: '0.55rem', color: 'var(--text-muted)' }}>{t}s</span>
          </div>
        })}
        {/* Subtitle blocks */}
        {subs.map((s, idx) => {
          const st = parseFloat(String(s.start)) || 0
          const en = parseFloat(String(s.end)) || 0
          if (en <= st) return null
          const left = (st / videoDuration) * 100
          const width = ((en - st) / videoDuration) * 100
          const isSelected = selectedIdx === idx
          const isDraggingThis = dragging?.idx === idx
          return (
            <div
              key={idx}
              title={`[${st.toFixed(1)}s - ${en.toFixed(1)}s] ${s.text}`}
              style={{
                position: 'absolute',
                left: `${left}%`, width: `${Math.max(width, 1)}%`,
                top: 4, height: 44,
                background: s.use_tts ? 'var(--accent)' : 'var(--info)',
                opacity: isDraggingThis ? 0.9 : isSelected ? 0.85 : 0.65,
                borderRadius: 4,
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                overflow: 'hidden', whiteSpace: 'nowrap',
                fontSize: '0.6rem', color: '#fff', padding: '0 12px',
                border: isSelected ? '2px solid #fff' : '1px solid rgba(255,255,255,0.2)',
                boxShadow: isSelected ? '0 0 8px rgba(0,0,0,0.3)' : 'none',
                zIndex: isSelected ? 2 : 1,
                transition: isDraggingThis ? 'none' : 'opacity 0.15s',
              }}
              onClick={(e) => { e.stopPropagation(); setSelectedIdx(idx); seekTo(st) }}
              onMouseDown={handleMouseDown(idx, 'move')}
            >
              {/* Left resize handle */}
              <div
                onMouseDown={handleMouseDown(idx, 'left')}
                style={{
                  position: 'absolute', left: 0, top: 0, bottom: 0, width: 8,
                  cursor: 'ew-resize', background: 'rgba(255,255,255,0.15)',
                  borderRadius: '4px 0 0 4px'
                }}
              />
              {/* Content */}
              <span style={{ pointerEvents: 'none', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                {s.text.slice(0, 20)}{s.text.length > 20 ? '...' : ''}
              </span>
              {/* Right resize handle */}
              <div
                onMouseDown={handleMouseDown(idx, 'right')}
                style={{
                  position: 'absolute', right: 0, top: 0, bottom: 0, width: 8,
                  cursor: 'ew-resize', background: 'rgba(255,255,255,0.15)',
                  borderRadius: '0 4px 4px 0'
                }}
              />
            </div>
          )
        })}
      </div>
      <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.6rem', color: 'var(--text-muted)', marginTop: 2 }}>
        <span>0s</span>
        <span>{videoDuration.toFixed(1)}s</span>
      </div>
    </div>
  )
}

// ─── Slide Card ──────────────────────────────
function SlideCard({ slide, index, total, projectId, onUpdate, onDelete, onMoveUp, onMoveDown, onPreviewImage, isSelected, onToggleSelect }: {
  slide: Slide; index: number; total: number; projectId: string
  onUpdate: (s: Slide) => void
  onDelete: () => void
  onMoveUp: () => void
  onMoveDown: () => void
  onPreviewImage?: (url: string) => void
  isSelected?: boolean
  onToggleSelect?: () => void
}) {
  const [text, setText] = useState(slide.text)
  const [volume, setVolume] = useState(slide.volume ?? 1.0)
  const [trimStart, setTrimStart] = useState<number>(slide.trim_start || 0)
  const [trimEnd, setTrimEnd] = useState<number>(slide.trim_end || 0)
  const [videoDuration, setVideoDuration] = useState<number>(0)
  const [useTts, setUseTts] = useState<boolean>((slide.use_tts ?? 1) === 1)
  const [subs, setSubs] = useState<SubEntry[]>(() => parseSubtitles(slide.subtitles))
  const [transition, setTransition] = useState<string>(slide.transition ?? 'none')
  const [ttsVolume, setTtsVolume] = useState(slide.tts_volume ?? 1.0)
  const [rotation, setRotation] = useState(slide.rotation ?? 0)
  const videoRef = useRef<HTMLVideoElement>(null)

  useEffect(() => { setText(slide.text) }, [slide.text])
  useEffect(() => { setVolume(slide.volume ?? 1.0) }, [slide.volume])
  useEffect(() => { setUseTts((slide.use_tts ?? 1) === 1) }, [slide.use_tts])
  useEffect(() => { setSubs(parseSubtitles(slide.subtitles)) }, [slide.subtitles])
  useEffect(() => { setTransition(slide.transition ?? 'none') }, [slide.transition])
  useEffect(() => { setTtsVolume(slide.tts_volume ?? 1.0) }, [slide.tts_volume])
  useEffect(() => { setRotation(slide.rotation ?? 0) }, [slide.rotation])

  const handleBlur = () => {
    if (text !== slide.text) onUpdate({ ...slide, text })
  }
  const handleTransitionChange = (val: string) => {
    setTransition(val)
    onUpdate({ ...slide, transition: val })
  }
  const handleVolumeChange = (v: number) => {
    setVolume(v)
    if (videoRef.current) videoRef.current.volume = v
    onUpdate({ ...slide, volume: v })
  }
  const handleSubChange = (idx: number, field: keyof SubEntry, val: string | boolean) => {
    const next = subs.map((s, i) => i === idx ? { ...s, [field]: val } : s)
    setSubs(next)
    onUpdate({ ...slide, subtitles: serializeSubtitles(next) })
  }
  const handleAddSub = () => {
    const next = [...subs, { start: '0:00', end: '0:05', text: '', use_tts: false }]
    setSubs(next)
    onUpdate({ ...slide, subtitles: serializeSubtitles(next) })
  }
  const handleDeleteSub = (idx: number) => {
    const next = subs.filter((_, i) => i !== idx)
    setSubs(next)
    onUpdate({ ...slide, subtitles: serializeSubtitles(next) })
  }

  const isVideo = slide.slide_type === 'video'

  return (
    <div className="card" style={{ padding: '1rem', display: 'grid', gridTemplateColumns: isVideo ? '1fr 40px' : '120px 1fr 40px', gap: '1rem', alignItems: 'start' }}>
      {/* Image Slide: Thumbnail */}
      {!isVideo && (
        <div style={{ borderRadius: 'var(--radius-sm)', overflow: 'hidden', background: 'var(--bg-secondary)', aspectRatio: '16/9', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
          {slide.image_filename ? (
            <img
              src={api.assetUrl(projectId, slide.image_filename)}
              alt={`Slide ${index + 1}`}
              style={{ width: '100%', height: '100%', objectFit: 'contain', cursor: onPreviewImage ? 'pointer' : 'default', transform: rotation ? `rotate(${rotation}deg)` : undefined }}
              onClick={() => onPreviewImage && onPreviewImage(api.assetUrl(projectId, slide.image_filename!))}
              onError={e => { (e.target as HTMLImageElement).src = '' }}
            />
          ) : (
            <span style={{ color: 'var(--text-muted)', fontSize: '1.5rem' }}>🖼️</span>
          )}
        </div>
      )}

      {/* Center Content */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          {!isVideo && onToggleSelect && (
            <input
              type="checkbox"
              checked={isSelected}
              onChange={onToggleSelect}
              style={{ cursor: 'pointer', transform: 'scale(1.2)' }}
            />
          )}
          <label className="label" style={{ margin: 0 }}>
            {isVideo ? '🎬' : '🖼️'} Slide {index + 1} — {slide.label || slide.video_filename || slide.image_filename}
          </label>
        </div>

        {/* Video Slide: preview + volume + subtitles */}
        {isVideo ? (
          <>
            {slide.video_filename && (
              <video
                ref={videoRef}
                controls
                style={{ width: '100%', maxHeight: 200, borderRadius: 'var(--radius-sm)', background: '#000', transform: rotation ? `rotate(${rotation}deg)` : undefined }}
                src={api.assetUrl(projectId, slide.video_filename)}
                onLoadedMetadata={e => {
                  const dur = (e.target as HTMLVideoElement).duration
                  if (dur && isFinite(dur)) setVideoDuration(dur)
                }}
              />
            )}
            {/* Volume */}
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <span style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', whiteSpace: 'nowrap' }}>🔊 볼륨</span>
              <input
                type="range" min={0} max={1} step={0.05}
                value={volume}
                style={{ flex: 1 }}
                onChange={e => handleVolumeChange(parseFloat(e.target.value))}
              />
              <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)', width: 36 }}>{Math.round(volume * 100)}%</span>
            </div>
            {/* Trimming — Dual Range Slider */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
              <span style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>✂️ 자르기</span>
              {videoDuration > 0 && (
                <div style={{ position: 'relative', height: 28, margin: '0 4px' }}>
                  {/* Highlight bar */}
                  <div style={{
                    position: 'absolute', top: 10, height: 8, borderRadius: 4,
                    background: 'var(--primary)',
                    left: `${(trimStart / videoDuration) * 100}%`,
                    right: `${100 - ((trimEnd || videoDuration) / videoDuration) * 100}%`,
                    opacity: 0.4, pointerEvents: 'none'
                  }} />
                  <input type="range" min={0} max={videoDuration} step={0.1}
                    value={trimStart}
                    style={{ position: 'absolute', width: '100%', top: 0, pointerEvents: 'none', appearance: 'none', background: 'transparent', zIndex: 2 }}
                    className="trim-range"
                    onChange={e => {
                      const v = Math.min(parseFloat(e.target.value), (trimEnd || videoDuration) - 0.1)
                      setTrimStart(v)
                    }}
                    onMouseUp={() => onUpdate({ ...slide, trim_start: trimStart })}
                  />
                  <input type="range" min={0} max={videoDuration} step={0.1}
                    value={trimEnd || videoDuration}
                    style={{ position: 'absolute', width: '100%', top: 0, pointerEvents: 'none', appearance: 'none', background: 'transparent', zIndex: 3 }}
                    className="trim-range"
                    onChange={e => {
                      const v = Math.max(parseFloat(e.target.value), trimStart + 0.1)
                      setTrimEnd(v >= videoDuration ? 0 : v)
                    }}
                    onMouseUp={() => onUpdate({ ...slide, trim_end: trimEnd })}
                  />
                </div>
              )}
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.75rem', color: 'var(--text-muted)' }}>
                <span>시작: {trimStart.toFixed(1)}s</span>
                <span>종료: {trimEnd ? `${trimEnd.toFixed(1)}s` : '끝까지'}</span>
                {videoDuration > 0 && <span>총: {videoDuration.toFixed(1)}s</span>}
              </div>
            </div>
            {/* Subtitle Row Editor */}
            <div>
              <div style={{ fontSize: '0.85rem', fontWeight: 600, marginBottom: '0.4rem', color: 'var(--text-secondary)' }}>📝 자막</div>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.8rem' }}>
                <thead>
                  <tr style={{ color: 'var(--text-muted)' }}>
                    <th style={{ padding: '2px 6px', textAlign: 'left', width: 72 }}>시작(초)</th>
                    <th style={{ padding: '2px 6px', textAlign: 'left', width: 72 }}>종료(초)</th>
                    <th style={{ padding: '2px 6px', textAlign: 'left' }}>자막 텍스트</th>
                    <th style={{ padding: '2px 6px', width: 44 }}>TTS</th>
                    <th style={{ width: 28 }}></th>
                  </tr>
                </thead>
                <tbody>
                  {subs.map((s, idx) => {
                    const startSec = parseFloat(String(s.start)) || 0
                    const endSec = parseFloat(String(s.end)) || 0
                    return (
                    <tr key={idx} style={{ borderTop: '1px solid var(--border)' }}>
                      <td style={{ padding: '3px 4px' }}>
                        <div style={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
                          <input type="number" className="input" style={{ padding: '2px 4px', fontSize: '0.78rem', width: 62 }}
                            value={startSec.toFixed(1)} step={0.1} min={0} max={videoDuration || 999}
                            onChange={e => handleSubChange(idx, 'start', e.target.value)}
                          />
                          {videoDuration > 0 && (
                            <input type="range" min={0} max={videoDuration} step={0.1} value={startSec}
                              style={{ width: 62, height: 12 }}
                              onChange={e => handleSubChange(idx, 'start', e.target.value)}
                              onMouseDown={() => { if (videoRef.current) videoRef.current.currentTime = startSec }}
                            />
                          )}
                        </div>
                      </td>
                      <td style={{ padding: '3px 4px' }}>
                        <div style={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
                          <input type="number" className="input" style={{ padding: '2px 4px', fontSize: '0.78rem', width: 62 }}
                            value={endSec.toFixed(1)} step={0.1} min={0} max={videoDuration || 999}
                            onChange={e => handleSubChange(idx, 'end', e.target.value)}
                          />
                          {videoDuration > 0 && (
                            <input type="range" min={0} max={videoDuration} step={0.1} value={endSec}
                              style={{ width: 62, height: 12 }}
                              onChange={e => handleSubChange(idx, 'end', e.target.value)}
                              onMouseDown={() => { if (videoRef.current) videoRef.current.currentTime = endSec }}
                            />
                          )}
                        </div>
                      </td>
                      <td style={{ padding: '3px 4px' }}>
                        <input className="input" style={{ padding: '2px 4px', fontSize: '0.78rem', width: '100%' }}
                          value={s.text} placeholder="자막 내용..."
                          onChange={e => handleSubChange(idx, 'text', e.target.value)}
                        />
                      </td>
                      <td style={{ padding: '3px 4px', textAlign: 'center' }}>
                        <input type="checkbox" checked={s.use_tts}
                          onChange={e => handleSubChange(idx, 'use_tts', e.target.checked)}
                          title="TTS 음성 생성"
                        />
                      </td>
                      <td style={{ padding: '3px 4px', textAlign: 'center' }}>
                        <button className="slide-ctrl-btn danger" style={{ width: 24, height: 24, fontSize: '0.7rem' }}
                          onClick={() => handleDeleteSub(idx)}>&#x2715;</button>
                      </td>
                    </tr>
                    )
                  })}
                </tbody>
              </table>
              <button className="btn btn-ghost" style={{ marginTop: '0.4rem', fontSize: '0.8rem', padding: '4px 10px' }}
                onClick={handleAddSub}>+ 자막 추가</button>

              {/* Subtitle Interactive Timeline (6-12) */}
              {subs.length > 0 && videoDuration > 0 && (
                <SubtitleTimeline
                  subs={subs}
                  videoDuration={videoDuration}
                  onChange={(newSubs) => {
                    setSubs(newSubs)
                    onUpdate({ ...slide, subtitles: serializeSubtitles(newSubs) })
                  }}
                  videoRef={videoRef}
                />
              )}
            </div>
            {/* TTS Volume (video slide) */}
            {subs.some(s => s.use_tts) && (
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                <span style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', whiteSpace: 'nowrap' }}>🗣️ TTS 볼륨</span>
                <input
                  type="range" min={0} max={2} step={0.05}
                  value={ttsVolume}
                  style={{ flex: 1 }}
                  onChange={e => {
                    const v = parseFloat(e.target.value)
                    setTtsVolume(v)
                    onUpdate({ ...slide, tts_volume: v })
                  }}
                />
                <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)', width: 36 }}>{Math.round(ttsVolume * 100)}%</span>
              </div>
            )}
          </>
        ) : (
          /* Image Slide: text + TTS 토글 */
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
            <textarea
              className="textarea"
              value={text}
              onChange={e => setText(e.target.value)}
              onBlur={() => { if (text !== slide.text) onUpdate({ ...slide, text }) }}
              placeholder="TTS 대사 / 자막 텍스트를 입력하세요..."
              rows={4}
            />
            <label style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', fontSize: '0.85rem', cursor: 'pointer', color: 'var(--text-secondary)' }}>
              <input
                type="checkbox"
                checked={useTts}
                onChange={e => {
                  const v = e.target.checked
                  setUseTts(v)
                  onUpdate({ ...slide, use_tts: v ? 1 : 0 })
                }}
              />
              🔊 TTS 음성 생성 {useTts ? '(켜짐 — 음성 + 자막)' : '(꺼짐 — 자막만)'}
            </label>
            {useTts && (
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                <span style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', whiteSpace: 'nowrap' }}>🗣️ TTS 볼륨</span>
                <input
                  type="range" min={0} max={2} step={0.05}
                  value={ttsVolume}
                  style={{ flex: 1 }}
                  onChange={e => {
                    const v = parseFloat(e.target.value)
                    setTtsVolume(v)
                    onUpdate({ ...slide, tts_volume: v })
                  }}
                />
                <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)', width: 36 }}>{Math.round(ttsVolume * 100)}%</span>
              </div>
            )}
          </div>
        )}
      </div>

      {/* Controls */}
      <div className="slide-controls">
        <button className="slide-ctrl-btn" title="위로" onClick={onMoveUp} disabled={index === 0}>&#x25B2;</button>
        <button className="slide-ctrl-btn" title="아래로" onClick={onMoveDown} disabled={index === total - 1}>&#x25BC;</button>
        <button className="slide-ctrl-btn" title={`회전 (현재 ${rotation}°)`} onClick={() => {
          const next = (rotation + 90) % 360
          setRotation(next)
          onUpdate({ ...slide, rotation: next })
        }}>&#x21BB;</button>
        <button className="slide-ctrl-btn danger" title="삭제" onClick={onDelete}>&#x2715;</button>
      </div>

      {/* Transition selector — 첫 슬라이드 제외 */}
      {index > 0 && (
        <div style={{
          gridColumn: '1 / -1',
          display: 'flex', alignItems: 'center', gap: '0.5rem',
          padding: '0.5rem 0.25rem 0',
          borderTop: '1px dashed var(--border)',
          marginTop: '0.25rem'
        }}>
          <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)', whiteSpace: 'nowrap' }}>🎬 이전 → 이 장면 전환:</span>
          <select
            className="input"
            value={transition}
            onChange={e => handleTransitionChange(e.target.value)}
            style={{ maxWidth: 200, padding: '0.25rem 0.5rem', fontSize: '0.8rem' }}
          >
            <option value="none">없음 (Hard Cut)</option>
            <option value="crossfade">크로스페이드 (Crossfade)</option>
            <option value="fade_black">페이드 투 블랙 (Fade to Black)</option>
            <option value="slide_left">슬라이드 왼쪽 (Slide Left)</option>
            <option value="slide_right">슬라이드 오른쪽 (Slide Right)</option>
          </select>
        </div>
      )}
    </div>
  )
}


// ─── Main Component ──────────────────────────
export default function Editor() {
  const { id: projectId } = useParams<{ id: string }>()
  const navigate = useNavigate()
  const { toast } = useToast()

  const [project, setProject] = useState<ProjectDetail | null>(null)
  const [slides, setSlides] = useState<Slide[]>([])
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [uploading, setUploading] = useState(false)
  const [rendering, setRendering] = useState(false)
  const [progress, setProgress] = useState(0)
  const [progressMsg, setProgressMsg] = useState('')
  const [insertAt, setInsertAt] = useState(-1)
  const [showJson, setShowJson] = useState(false)
  const [showYoutube, setShowYoutube] = useState(false)
  const [showPhotos, setShowPhotos] = useState(false)
  const [showSettings, setShowSettings] = useState(false)
  const [isDragging, setIsDragging] = useState(false)
  const [previewImage, setPreviewImage] = useState<string | null>(null)
  const [selectedSlideIds, setSelectedSlideIds] = useState<Set<string>>(new Set())
  const [collageLayout, setCollageLayout] = useState('auto')
  const [dragIdx, setDragIdx] = useState<number | null>(null)
  const [dropIdx, setDropIdx] = useState<number | null>(null)
  const [activeSlideIdx, setActiveSlideIdx] = useState<number | null>(null)

  const fileInputRef = useRef<HTMLInputElement>(null)
  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null)
  const slideRefs = useRef<Map<number, HTMLDivElement>>(new Map())

  const loadProject = useCallback(async () => {
    if (!projectId) return
    try {
      const data = await api.getProject(projectId)
      setProject(data)
      setSlides(data.slides)
      if (['QUEUED', 'PROCESSING'].includes(data.status)) {
        setRendering(true)
        setProgress(data.progress)
        setProgressMsg(data.message)
      } else {
        setRendering(false)
      }
    } catch (e) {
      toast('프로젝트를 불러올 수 없습니다', 'error')
      navigate('/')
    } finally {
      setLoading(false)
    }
  }, [projectId, navigate, toast])

  useEffect(() => { loadProject() }, [loadProject])

  // Render polling
  useEffect(() => {
    if (!rendering || !projectId) { if (pollRef.current) clearInterval(pollRef.current); return }
    pollRef.current = setInterval(async () => {
      try {
        const s = await api.getRenderStatus(projectId)
        setProgress(s.progress)
        setProgressMsg(s.message)
        if (!['QUEUED', 'PROCESSING'].includes(s.status)) {
          setRendering(false)
          clearInterval(pollRef.current!)
          await loadProject()
          if (s.status === 'COMPLETED') toast('🎉 렌더링 완료!', 'success')
          else if (s.status === 'ERROR') toast(`오류: ${s.message}`, 'error')
        }
      } catch { clearInterval(pollRef.current!) }
    }, 2000)
    return () => { if (pollRef.current) clearInterval(pollRef.current) }
  }, [rendering, projectId, loadProject, toast])

  const handleSave = async () => {
    if (!projectId) return
    setSaving(true)
    try {
      const reindexed = slides.map((s, i) => ({ ...s, order_index: i }))
      await api.saveSlides(projectId, reindexed)
      setSlides(reindexed)
      toast('저장 완료', 'success')
    } catch (e: unknown) {
      toast(e instanceof Error ? e.message : '저장 실패', 'error')
    } finally {
      setSaving(false)
    }
  }

  const processFiles = async (files: File[]) => {
    if (!files.length || !projectId) return
    setUploading(true)
    try {
      const newSlides = await api.uploadSlides(projectId, files, insertAt)
      setSlides(prev => {
        const insertIdx = insertAt === -1 ? prev.length : Math.min(insertAt, prev.length)
        const updated = [...prev.slice(0, insertIdx), ...newSlides, ...prev.slice(insertIdx)]
        return updated.map((s, idx) => ({ ...s, order_index: idx }))
      })
      toast(`${newSlides.length}장 업로드 완료!`, 'success')
      setInsertAt(-1)
    } catch (e: unknown) {
      toast(e instanceof Error ? e.message : '업로드 실패', 'error')
    } finally {
      setUploading(false)
      if (fileInputRef.current) fileInputRef.current.value = ''
    }
  }

  const handleUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    processFiles(Array.from(e.target.files || []))
  }

  const handleCreateCollage = async () => {
    if (!projectId || selectedSlideIds.size < 2) return
    setUploading(true)
    try {
      const slideIds = Array.from(selectedSlideIds)
      const newSlide = await api.createCollage(projectId, slideIds, collageLayout)

      setSlides(prev => {
        // Remove the chosen slides from state
        const remaining = prev.filter(s => !selectedSlideIds.has(s.id))
        // Put the new slide sorted via order_index
        const updated = [...remaining]
        updated.splice(newSlide.order_index, 0, newSlide)
        return updated.map((s, idx) => ({ ...s, order_index: idx }))
      })
      toast('콜라주 생성 완료!', 'success')
      setSelectedSlideIds(new Set())
    } catch (err: unknown) {
      toast(err instanceof Error ? err.message : '콜라주 생성 실패', 'error')
    } finally {
      setUploading(false)
    }
  }

  const toggleSelectSlide = (id: string) => {
    setSelectedSlideIds(prev => {
      const next = new Set(prev)
      if (next.has(id)) next.delete(id)
      else next.add(id)
      return next
    })
  }

  // Drag & Drop Handlers
  const onDragOver = (e: React.DragEvent) => {
    e.preventDefault()
    e.stopPropagation()
    setIsDragging(true)
  }

  const onDragLeave = (e: React.DragEvent) => {
    e.preventDefault()
    e.stopPropagation()
    setIsDragging(false)
  }

  const onDrop = (e: React.DragEvent) => {
    e.preventDefault()
    e.stopPropagation()
    setIsDragging(false)
    if (e.dataTransfer.files && e.dataTransfer.files.length > 0) {
      processFiles(Array.from(e.dataTransfer.files))
    }
  }

  const handleRender = async () => {
    if (!projectId) return
    const unsaved = slides.map((s, i) => ({ ...s, order_index: i }))
    await api.saveSlides(projectId, unsaved)
    try {
      await api.startRender(projectId)
      setRendering(true)
      setProgress(0)
      setProgressMsg('렌더링 대기 중...')
      toast('렌더링 시작됨', 'info')
    } catch (e: unknown) {
      toast(e instanceof Error ? e.message : '렌더링 시작 실패', 'error')
    }
  }

  const moveSlide = (i: number, dir: -1 | 1) => {
    const arr = [...slides]
      ;[arr[i], arr[i + dir]] = [arr[i + dir], arr[i]]
    setSlides(arr)
  }

  // 6-1: Slide drag & drop reorder
  const handleSlideDragStart = (idx: number) => (e: React.DragEvent) => {
    setDragIdx(idx)
    e.dataTransfer.effectAllowed = 'move'
    e.dataTransfer.setData('text/plain', String(idx))
  }
  const handleSlideDragOver = (idx: number) => (e: React.DragEvent) => {
    e.preventDefault()
    e.dataTransfer.dropEffect = 'move'
    if (dragIdx !== null && idx !== dragIdx) setDropIdx(idx)
  }
  const handleSlideDrop = (idx: number) => (e: React.DragEvent) => {
    e.preventDefault()
    if (dragIdx === null || dragIdx === idx) { setDragIdx(null); setDropIdx(null); return }
    const arr = [...slides]
    const [moved] = arr.splice(dragIdx, 1)
    arr.splice(idx, 0, moved)
    setSlides(arr)
    setDragIdx(null)
    setDropIdx(null)
  }
  const handleSlideDragEnd = () => { setDragIdx(null); setDropIdx(null) }

  // 6-4: Scroll to slide card from thumbnail
  const scrollToSlide = (idx: number) => {
    setActiveSlideIdx(idx)
    slideRefs.current.get(idx)?.scrollIntoView({ behavior: 'smooth', block: 'center' })
  }

  const deleteSlide = async (i: number) => {
    if (!projectId) return
    const slide = slides[i]
    try {
      await api.deleteSlide(projectId, slide.id)
      setSlides(prev => prev.filter((_, idx) => idx !== i))
    } catch (e: unknown) {
      toast(e instanceof Error ? e.message : '삭제 실패', 'error')
    }
  }

  const updateSlide = (i: number, updated: Slide) => {
    setSlides(prev => prev.map((s, idx) => idx === i ? updated : s))
  }

  if (loading) return (
    <div style={{ display: 'flex', justifyContent: 'center', padding: '6rem' }}>
      <span className="spinner spinner-lg" />
    </div>
  )

  const hasVideo = project?.has_video
  const isActive = rendering

  return (
    <div
      style={{ display: 'grid', gridTemplateColumns: '260px 120px 1fr', minHeight: 'calc(100vh - 64px)', position: 'relative' }}
      onDragOver={onDragOver}
      onDragLeave={onDragLeave}
      onDrop={onDrop}
    >
      {/* Drag overlay */}
      {isDragging && (
        <div style={{
          position: 'absolute', top: 0, left: 0, right: 0, bottom: 0,
          background: 'rgba(59, 130, 246, 0.15)', backdropFilter: 'blur(2px)',
          border: '3px dashed var(--primary)', borderRadius: 'var(--radius-lg)',
          zIndex: 50, display: 'flex', alignItems: 'center', justifyContent: 'center',
          pointerEvents: 'none'
        }}>
          <div style={{ background: 'var(--bg-card)', padding: '2rem 3rem', borderRadius: 'var(--radius-md)', boxShadow: 'var(--shadow-lg)' }}>
            <h2 style={{ fontSize: '1.5rem', color: 'var(--primary)', margin: 0 }}>📁 여기에 파일 드롭</h2>
            <p style={{ marginTop: '0.5rem', color: 'var(--text-muted)' }}>여러 장의 이미지나 PDF를 한 번에 추가할 수 있습니다</p>
          </div>
        </div>
      )}

      {/* Sidebar */}
      <aside style={{ background: 'var(--bg-secondary)', borderRight: '1px solid var(--border)', padding: '1rem 0.85rem', display: 'flex', flexDirection: 'column', gap: '0.6rem', position: 'sticky', top: '64px', height: 'calc(100vh - 64px)', overflowY: 'auto' }}>
        <button className="action-card" onClick={() => navigate('/')} style={{ padding: '0.45rem 0.65rem' }}>
          <div className="action-icon" style={{ background: 'var(--bg-secondary)', width: 28, height: 28, fontSize: '0.85rem' }}>&#x2190;</div>
          <span style={{ fontSize: '0.8rem', fontWeight: 500 }}>목록으로</span>
        </button>

        <hr className="divider" style={{ margin: '0.25rem 0' }} />

        {/* ── Upload Section ── */}
        <div className="sidebar-section-title">&#x1F4E4; 미디어 추가</div>
        <div style={{ marginBottom: '0.15rem' }}>
          <select
            className="input"
            value={insertAt}
            onChange={e => setInsertAt(Number(e.target.value))}
            style={{ width: '100%', padding: '0.35rem 0.5rem', fontSize: '0.78rem' }}
          >
            <option value={-1}>맨 끝에 추가</option>
            {slides.map((_, i) => (
              <option key={i} value={i}>{i + 1}번 슬라이드 앞에</option>
            ))}
          </select>
        </div>
        <input
          ref={fileInputRef}
          type="file"
          accept="image/*,.pdf,video/mp4,video/webm,video/quicktime,video/x-msvideo,video/x-matroska"
          multiple={true}
          style={{ display: 'none' }}
          onChange={handleUpload}
          id="file-upload"
        />
        <label htmlFor="file-upload" className="upload-zone">
          {uploading ? (
            <><span className="spinner" /><span className="upload-title">업로드 중...</span></>
          ) : (
            <>
              <span className="upload-icon">&#x1F4C1;</span>
              <span className="upload-title">파일 선택 / 드래그</span>
              <span className="upload-hint">이미지, PDF, 영상 지원</span>
            </>
          )}
        </label>
        <button className="action-card" onClick={() => setShowPhotos(true)}>
          <div className="action-icon" style={{ background: 'rgba(34,197,94,0.12)' }}>&#x1F4F7;</div>
          <div className="action-label">
            <span>Google Photos</span>
            <span>사진 가져오기</span>
          </div>
        </button>

        <hr className="divider" style={{ margin: '0.25rem 0' }} />

        {/* ── Settings Section ── */}
        <div className="sidebar-section-title">&#x2699;&#xFE0F; 프로젝트 설정</div>
        <button className="action-card" onClick={() => setShowSettings(true)} style={{ padding: '0.45rem 0.65rem' }}>
          <div className="action-icon" style={{ background: 'rgba(139,92,246,0.12)', width: 28, height: 28, fontSize: '0.85rem' }}>&#x2699;</div>
          <div className="action-label">
            <span>전역 설정 (Master)</span>
            <span>전환, 자막, 워터마크 등</span>
          </div>
        </button>

        {/* Aspect Ratio */}
        <div>
          <label className="label" style={{ fontSize: '0.72rem' }}>화면 비율</label>
          <select
            className="input"
            value={project?.aspect_ratio || '16:9'}
            onChange={async e => {
              if (!projectId || !project) return
              const val = e.target.value
              try {
                const updated = await api.updateSettings(projectId, { bgm_volume: project.bgm_volume ?? 0.3, aspect_ratio: val, tts_master_volume: project.tts_master_volume ?? 1.0 })
                setProject(prev => prev ? { ...prev, aspect_ratio: updated.aspect_ratio } : prev)
                toast(`화면 비율: ${val}`, 'success')
              } catch { toast('설정 저장 실패', 'error') }
            }}
            style={{ width: '100%', padding: '0.35rem 0.5rem', fontSize: '0.78rem' }}
          >
            <option value="16:9">16:9 (가로)</option>
            <option value="9:16">9:16 (세로)</option>
            <option value="1:1">1:1 (정사각형)</option>
          </select>
        </div>

        {/* BGM */}
        <div>
          <label className="label" style={{ fontSize: '0.72rem' }}>BGM 배경음악</label>
          {project?.bgm_filename ? (
            <div style={{ background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 'var(--radius-md)', padding: '0.5rem 0.6rem' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', fontSize: '0.78rem', color: 'var(--text-secondary)', marginBottom: '0.35rem' }}>
                <span style={{ fontSize: '1rem' }}>&#x1F3B5;</span>
                <span style={{ flex: 1, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                  {project.bgm_filename.replace('bgm_', '')}
                </span>
                <button className="slide-ctrl-btn danger" style={{ width: 22, height: 22, fontSize: '0.7rem' }}
                  onClick={async () => {
                    if (!projectId) return
                    try {
                      const updated = await api.deleteBgm(projectId)
                      setProject(prev => prev ? { ...prev, bgm_filename: updated.bgm_filename } : prev)
                      toast('BGM 삭제됨', 'info')
                    } catch { toast('BGM 삭제 실패', 'error') }
                  }}>&#x2715;</button>
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)', whiteSpace: 'nowrap' }}>볼륨</span>
                <input type="range" min={0} max={1} step={0.05}
                  value={project.bgm_volume ?? 0.3}
                  style={{ flex: 1 }}
                  onChange={e => {
                    const v = parseFloat(e.target.value)
                    setProject(prev => prev ? { ...prev, bgm_volume: v } : prev)
                  }}
                  onMouseUp={async () => {
                    if (!projectId || !project) return
                    try { await api.updateSettings(projectId, { bgm_volume: project.bgm_volume ?? 0.3, aspect_ratio: project.aspect_ratio || '16:9', tts_master_volume: project.tts_master_volume ?? 1.0 }) }
                    catch { toast('설정 저장 실패', 'error') }
                  }}
                />
                <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)', width: 30 }}>{Math.round((project.bgm_volume ?? 0.3) * 100)}%</span>
              </div>
            </div>
          ) : (
            <>
              <input
                type="file" accept="audio/*" style={{ display: 'none' }} id="bgm-upload"
                onChange={async e => {
                  const file = e.target.files?.[0]
                  if (!file || !projectId) return
                  try {
                    const updated = await api.uploadBgm(projectId, file)
                    setProject(prev => prev ? { ...prev, bgm_filename: updated.bgm_filename, bgm_volume: updated.bgm_volume } : prev)
                    toast('BGM 업로드 완료', 'success')
                  } catch { toast('BGM 업로드 실패', 'error') }
                  e.target.value = ''
                }}
              />
              <label htmlFor="bgm-upload" className="action-card" style={{ cursor: 'pointer' }}>
                <div className="action-icon" style={{ background: 'rgba(245,158,11,0.12)' }}>&#x1F3B5;</div>
                <div className="action-label">
                  <span>BGM 추가</span>
                  <span>오디오 파일 업로드</span>
                </div>
              </label>
            </>
          )}
        </div>

        {/* Master TTS Volume */}
        {project && (
          <div>
            <label className="label" style={{ fontSize: '0.72rem' }}>Master TTS 볼륨</label>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
              <input type="range" min={0} max={2} step={0.05}
                value={project.tts_master_volume ?? 1.0}
                style={{ flex: 1 }}
                onChange={e => {
                  const v = parseFloat(e.target.value)
                  setProject(prev => prev ? { ...prev, tts_master_volume: v } : prev)
                }}
                onMouseUp={async () => {
                  if (!projectId || !project) return
                  try {
                    await api.updateSettings(projectId, {
                      bgm_volume: project.bgm_volume ?? 0.3,
                      aspect_ratio: project.aspect_ratio || '16:9',
                      tts_master_volume: project.tts_master_volume ?? 1.0,
                    })
                  } catch { toast('설정 저장 실패', 'error') }
                }}
              />
              <span style={{ fontSize: '0.72rem', color: 'var(--text-muted)', width: 36 }}>{Math.round((project.tts_master_volume ?? 1.0) * 100)}%</span>
            </div>
            <span style={{ fontSize: '0.65rem', color: 'var(--text-muted)' }}>개별 TTS 볼륨에 곱해집니다</span>
          </div>
        )}

        <hr className="divider" style={{ margin: '0.25rem 0' }} />

        {/* ── Tools Section ── */}
        <div className="sidebar-section-title">&#x1F6E0;&#xFE0F; 도구</div>
        <button className="action-card" onClick={() => setShowJson(true)}>
          <div className="action-icon" style={{ background: 'rgba(59,130,246,0.12)' }}>&#x007B;&#x007D;</div>
          <div className="action-label">
            <span>JSON 일괄 입력</span>
            <span>대사 텍스트 일괄 적용</span>
          </div>
        </button>
        <button className="action-card" onClick={() => {
          const trans = project?.default_transition || 'none'
          const updated = slides.map((s, i) => i === 0 ? s : { ...s, transition: trans })
          setSlides(updated)
          toast(`전체 전환 효과: ${trans === 'none' ? '없음' : trans}`, 'success')
        }} style={{ padding: '0.45rem 0.65rem' }}>
          <div className="action-icon" style={{ background: 'rgba(168,85,247,0.12)', width: 28, height: 28, fontSize: '0.85rem' }}>&#x21C4;</div>
          <div className="action-label">
            <span>전환 일괄 적용</span>
            <span>전역 설정 값으로 통일</span>
          </div>
        </button>
        <button className="action-card" onClick={() => {
          const allOn = slides.every(s => s.use_tts === 1)
          const updated = slides.map(s => s.slide_type === 'image' ? { ...s, use_tts: allOn ? 0 : 1 } : s)
          setSlides(updated)
          toast(allOn ? 'TTS 전체 OFF' : 'TTS 전체 ON', 'info')
        }} style={{ padding: '0.45rem 0.65rem' }}>
          <div className="action-icon" style={{ background: 'rgba(14,165,233,0.12)', width: 28, height: 28, fontSize: '0.85rem' }}>&#x1F50A;</div>
          <div className="action-label">
            <span>TTS 일괄 On/Off</span>
            <span>이미지 슬라이드 전체 토글</span>
          </div>
        </button>

        <hr className="divider" style={{ margin: '0.25rem 0' }} />

        {/* ── Actions Section ── */}
        <div className="sidebar-section-title">&#x25B6;&#xFE0F; 실행</div>
        <button className="btn-action-primary save" onClick={handleSave} disabled={saving}>
          {saving ? <><span className="spinner" /> 저장 중...</> : '저장'}
        </button>
        <button className="btn-action-primary render" onClick={handleRender} disabled={isActive || slides.length === 0}>
          {isActive ? <><span className="spinner" /> 렌더링 중...</> : '렌더링 시작'}
        </button>

        {/* Render Progress */}
        {isActive && (
          <div style={{ background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 'var(--radius-md)', padding: '0.6rem' }}>
            <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)', marginBottom: '0.35rem' }}>
              {progressMsg} ({progress}%)
            </div>
            <div className="progress-bar-wrap">
              <div className="progress-bar-fill animate-pulse" style={{ width: `${Math.max(5, progress)}%` }} />
            </div>
          </div>
        )}

        {/* Render Error */}
        {!isActive && project?.status === 'ERROR' && (
          <div style={{
            background: 'rgba(239,68,68,0.1)', border: '1px solid rgba(239,68,68,0.4)',
            borderRadius: 'var(--radius-md)', padding: '0.65rem', fontSize: '0.75rem'
          }}>
            <div style={{ color: '#f87171', fontWeight: 700, marginBottom: '0.25rem' }}>렌더링 실패</div>
            <div style={{ color: 'var(--text-muted)', whiteSpace: 'pre-wrap', wordBreak: 'break-word' }}>{project.message}</div>
          </div>
        )}

        {/* ── Output Section ── */}
        {hasVideo && (
          <>
            <hr className="divider" style={{ margin: '0.25rem 0' }} />
            <div className="sidebar-section-title">&#x1F3AC; 결과물</div>
            <div>
              <video
                key={api.downloadUrl(projectId!)}
                controls
                style={{ width: '100%', borderRadius: 'var(--radius-md)', border: '1px solid var(--border)', background: '#000' }}
              >
                <source src={api.downloadUrl(projectId!)} type="video/mp4" />
              </video>
            </div>
            <div className="action-grid">
              <a className="action-grid-item" href={api.downloadUrl(projectId!)} download>
                <span className="grid-icon">&#x1F4E5;</span>
                <span>MP4 다운로드</span>
              </a>
              <button className="action-grid-item" onClick={() => setShowYoutube(true)}>
                <span className="grid-icon">&#x25B6;&#xFE0F;</span>
                <span>YouTube 업로드</span>
              </button>
            </div>
          </>
        )}

      </aside>

      {/* Thumbnail Panel (6-2 + 6-4) */}
      <div style={{
        background: 'var(--bg-secondary)', borderRight: '1px solid var(--border)',
        position: 'sticky', top: '64px', height: 'calc(100vh - 64px)', overflowY: 'auto',
        padding: '0.5rem', display: 'flex', flexDirection: 'column', gap: '4px'
      }}>
        <div style={{ fontSize: '0.65rem', color: 'var(--text-muted)', textAlign: 'center', fontWeight: 600, padding: '0.25rem 0' }}>
          슬라이드 ({slides.length})
        </div>
        {slides.map((slide, idx) => {
          const isVideo = slide.slide_type === 'video'
          const isActive = activeSlideIdx === idx
          return (
            <div
              key={slide.id}
              onClick={() => scrollToSlide(idx)}
              draggable
              onDragStart={handleSlideDragStart(idx)}
              onDragOver={handleSlideDragOver(idx)}
              onDrop={handleSlideDrop(idx)}
              onDragEnd={handleSlideDragEnd}
              style={{
                cursor: 'pointer',
                borderRadius: 'var(--radius-sm)',
                border: isActive ? '2px solid var(--accent)' : dropIdx === idx ? '2px dashed var(--accent)' : '2px solid transparent',
                background: isActive ? 'var(--accent-light)' : 'var(--bg-card)',
                padding: '2px',
                opacity: dragIdx === idx ? 0.4 : 1,
                transition: 'all 0.15s ease'
              }}
            >
              <div style={{ aspectRatio: '16/9', borderRadius: 3, overflow: 'hidden', background: '#000', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                {isVideo ? (
                  <span style={{ fontSize: '1.2rem' }}>🎬</span>
                ) : slide.image_filename ? (
                  <img
                    src={api.assetUrl(projectId!, slide.image_filename)}
                    alt=""
                    style={{ width: '100%', height: '100%', objectFit: 'cover' }}
                    onError={e => { (e.target as HTMLImageElement).style.display = 'none' }}
                  />
                ) : (
                  <span style={{ fontSize: '1rem', color: 'var(--text-muted)' }}>🖼️</span>
                )}
              </div>
              <div style={{ fontSize: '0.6rem', color: 'var(--text-muted)', textAlign: 'center', marginTop: 2, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                {idx + 1}
              </div>
            </div>
          )
        })}
      </div>

      {/* Main Content */}
      <main className="page" style={{ padding: '1.5rem' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>
          <div>
            <h2 style={{ fontSize: '1.4rem', fontWeight: 700 }}>📝 {project?.name}</h2>
            <p style={{ color: 'var(--text-muted)', fontSize: '0.8rem' }}>
              {slides.length} 슬라이드 · 변경 후 저장하거나 바로 렌더링하세요
            </p>
          </div>
        </div>

        {slides.length === 0 ? (
          <div className="empty-state">
            <div className="icon">🖼️</div>
            <h3>슬라이드가 없습니다</h3>
            <p>왼쪽 사이드바에서 이미지 또는 PDF를 업로드하세요</p>
          </div>
        ) : (
          <>
            <div style={{ display: 'flex', gap: '0.5rem', marginBottom: '1rem', alignItems: 'center' }}>
              <div style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>
                총 {slides.length}장
              </div>

              <div style={{ flex: 1 }} />

              {selectedSlideIds.size >= 2 && selectedSlideIds.size <= 4 && (
                <>
                  <select
                    className="input"
                    value={collageLayout}
                    onChange={e => setCollageLayout(e.target.value)}
                    style={{ width: 'auto', padding: '0.25rem 0.5rem', fontSize: '0.8rem' }}
                  >
                    <option value="auto">자동 배치</option>
                    <option value="horizontal">가로 나열</option>
                    <option value="2x2">2x2 그리드</option>
                    <option value="3x1">3x1 가로</option>
                    <option value="1x3">1x3 세로</option>
                  </select>
                  <button
                    className="btn btn-primary"
                    onClick={handleCreateCollage}
                    disabled={uploading}
                  >
                    🖼️ 콜라주로 합치기 ({selectedSlideIds.size}장)
                  </button>
                </>
              )}
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
              {slides.map((slide, i) => (
                <div
                  key={slide.id}
                  ref={el => { if (el) slideRefs.current.set(i, el); else slideRefs.current.delete(i) }}
                  draggable
                  onDragStart={handleSlideDragStart(i)}
                  onDragOver={handleSlideDragOver(i)}
                  onDrop={handleSlideDrop(i)}
                  onDragEnd={handleSlideDragEnd}
                  onClick={() => setActiveSlideIdx(i)}
                  style={{
                    opacity: dragIdx === i ? 0.4 : 1,
                    borderLeft: dropIdx === i ? '3px solid var(--accent)' : '3px solid transparent',
                    transition: 'opacity 0.15s, border-color 0.15s'
                  }}
                >
                  <SlideCard
                    slide={slide}
                    index={i}
                    total={slides.length}
                    projectId={projectId!}
                    onUpdate={s => updateSlide(i, s)}
                    onDelete={() => {
                      deleteSlide(i)
                      if (selectedSlideIds.has(slide.id)) {
                        setSelectedSlideIds(prev => {
                          const next = new Set(prev)
                          next.delete(slide.id)
                          return next
                        })
                      }
                    }}
                    onMoveUp={() => moveSlide(i, -1)}
                    onMoveDown={() => moveSlide(i, 1)}
                    onPreviewImage={url => setPreviewImage(url)}
                    isSelected={selectedSlideIds.has(slide.id)}
                    onToggleSelect={() => toggleSelectSlide(slide.id)}
                  />
                </div>
              ))}
            </div>
          </>
        )}
      </main>

      {/* Modals */}
      {showJson && (
        <JsonModal
          slides={slides}
          onApply={s => setSlides(s)}
          onClose={() => setShowJson(false)}
        />
      )}
      {showYoutube && project && (
        <YouTubeModal
          projectId={projectId!}
          projectName={project.name}
          onClose={() => setShowYoutube(false)}
        />
      )}
      {showPhotos && (
        <GooglePhotosModal
          projectId={projectId!}
          onClose={() => setShowPhotos(false)}
          onImported={loadProject}
        />
      )}
      {showSettings && project && (
        <GlobalSettingsModal
          project={project}
          onClose={() => setShowSettings(false)}
          onSave={async (settings) => {
            if (!projectId) return
            try {
              const updated = await api.updateSettings(projectId, {
                bgm_volume: project.bgm_volume ?? 0.3,
                aspect_ratio: project.aspect_ratio || '16:9',
                tts_master_volume: project.tts_master_volume ?? 1.0,
                ...settings,
              })
              setProject(prev => prev ? { ...prev, ...updated } : prev)
              toast('전역 설정 저장 완료', 'success')
              setShowSettings(false)
            } catch { toast('설정 저장 실패', 'error') }
          }}
        />
      )}

      {/* Image Preview Modal */}
      {previewImage && (
        <div className="modal-overlay" onClick={() => setPreviewImage(null)} style={{ zIndex: 9999, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '2rem' }}>
          <div style={{ position: 'relative', maxWidth: '100%', maxHeight: '100%', display: 'flex', flexDirection: 'column', alignItems: 'center' }} onClick={e => e.stopPropagation()}>
            <div style={{ width: '100%', display: 'flex', justifyContent: 'flex-end', marginBottom: '0.5rem' }}>
              <button className="btn btn-ghost btn-icon" onClick={() => setPreviewImage(null)} style={{ background: 'var(--bg-card)', color: 'var(--text)', borderRadius: '50%', width: '36px', height: '36px', display: 'flex', alignItems: 'center', justifyContent: 'center', boxShadow: 'var(--shadow)' }}>✕</button>
            </div>
            <img src={previewImage} alt="Preview" style={{ maxWidth: '100%', maxHeight: 'calc(100vh - 6rem)', objectFit: 'contain', borderRadius: 'var(--radius-md)', boxShadow: '0 10px 25px rgba(0,0,0,0.5)' }} />
          </div>
        </div>
      )}
    </div>
  )
}
